### ISSUE TITLE
 can't deny location permission twice

### ISSUE THREAD

**Issue by Flattih** [leancodepl/patrol#1663] opened 2023-08-25 21:24 UTC
### Steps to reproduce

1-run with patrol develop --target integration_test/local_test.dart --verbose
In the first dialog, deny permission works, in the second it does not work, but the allow part works.

### Actual results

    final isPermissionDialogVisible = await $.native.isPermissionDialogVisible();
    expect(isPermissionDialogVisible, true);
    await $.native.denyPermission();
    
    await $.pumpAndSettle();

    expect($(LocaleKeys.ENABLE_LOCATION.tr()), findsOneWidget);
    await Future.delayed(Duration(seconds: 1));

    await $(LocaleKeys.ENABLE_LOCATION.tr()).tap(
      settlePolicy: SettlePolicy.noSettle,
    );
    
    //deny permission again
    await $.native.isPermissionDialogVisible();

    await $.native.denyPermission();  //  Here it works if we allow location instead of deny.
  
 
 

### Logs

<details>
<summary>Logs</summary>

```
<!-- Patrol (native): isPermissionDialogVisible() started
        Patrol (native): isPermissionDialogVisible() succeeded
        Patrol (native): denyPermission() started
Patrol (native): denyPermission() failed
        ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
        The following PatrolActionException was thrown running a test:
        Patrol action failed: GrpcError: denyPermission() failed with code NOT_FOUND (selector button to
        deny permission found nothing)

        When the exception was thrown, this was the stack:
        #0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:236:7)
        <asynchronous suspension>
        #1      NativeAutomator.denyPermission (package:patrol/src/native/native_automator.dart:775:5)
        <asynchronous suspension>
        #2      main.<anonymous closure> (file:///Users/fatihpc/NewsAppFrontend/integration_test/local_screen_test.dart:36:5)
        <asynchronous suspension>
        #3      patrolTest.<anonymous closure> (package:patrol/src/common.dart:129:7)
        <asynchronous suspension>
        #4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:15)
        <asynchronous suspension>
        #5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:986:5)
        <asynchronous suspension>

        The test description was:
          Local screen test -->
```

</details>

### Patrol version

patrol: ^2.2.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Patrol CLI version: 2.1.2-->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- [✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64 (Rosetta), locale tr-TR)
    • Flutter version 3.10.6 on channel stable at /Users/fatihpc/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (6 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/fatihpc/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Users/fatihpc/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64 (Rosetta)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found! -->
```

</details>

**Comment by zmeid** [comment] 2023-09-01 18:59
I hit the same issue. I also tried tapping on "Don't allow" when denying the location permission the second time:

$.native.tap(Selector(text: "Don't allow"));

But, that did not work.

Patrol folks, any idea?

**Comment by Flattih** [comment] 2023-09-11 19:07
> This looks like a duplicate of #1647, can you confirm?

We refuse in the application, then we want to get the location information again by pressing the button without leaving the application, we cannot refuse again.

**Comment by bartekpacia** [comment] 2023-10-26 18:40
Closing because no [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) was provided.

Feel free to open a new issue with all the required information provided.

**Closed by bartekpacia** 2023-10-26 18:40 UTC
