### ISSUE TITLE
test always is PASS regardless of the actual code

### ISSUE THREAD

**Issue by markwigzell** [leancodepl/patrol#937] opened 2023-02-15 19:25 UTC
I have an example app folder inside of a flutter package that only has the actual implementation of an API.  It is for permissions, and I don't really want to test the example app at all, just the permissions implementation. 
Running my integration_test/app_test.dart I get: 

marks-macbook-p:example wigzm001$ patrol test --target integration_test/app_test.dart --device=emulator-5554 --package-name=com.disney.mobile_chassis.permissions.example
• Building apk with entrypoint app_test.dart...
✓ Completed building apk with entrypoint app_test.dart (8.0s)
• Executing tests of apk with entrypoint app_test.dart on emulator-5554...
✓ Completed executing apk with entrypoint app_test.dart on emulator-5554 (3.7s)
 PASS  app_test.dart on emulator-5554

Expected: code only passes if it succeeds
Actual: code passes always.

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel main, 3.8.0-12.0.pre.31, on macOS 12.6 21G115 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

The code in app_test.dart is:

import 'package:flutter_test/flutter_test.dart';
import 'package:mobile_chassis_permissions/src/permissions_impl.dart';
import 'package:patrol/patrol.dart';
import 'package:mobile_chassis_permissions/mobile_chassis_permissions.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:example/main.dart';

void main() {

  patrolTest('request storage permission', (PatrolTester $) async {

    var permissions = PermissionsImpl();
    final requestFuture = permissions.requestStorage();
    await $.native.grantPermissionWhenInUse();
    final result = await requestFuture;
    expect(result, equals(PermissionsStatus.denied));

    await $.pumpWidgetAndSettle(const ProviderScope(child: MyApp()));
  });
}

As you can see, I am just running "requestStorage()" method of the PermissionsImpl class. I don't really even care about the widgets. I played with changing the PermissionsStatus.granted to PermissionsStatus.denied, expecting that it fail. 

I followed a template I saw in the Patrol doc:

// 1. request the permission
final permissionRequestFuture = Geolocator.requestPermission();
// 2. grant the permission using Patrol
await $.native.grantPermissionWhenInUse();
// 3. wait for permission being granted
final permissionRequestResult = await permissionRequestFuture;
expect(permissionRequestResult, equals(LocationPermission.whileInUse));
final position = await Geolocator.getCurrentPosition();
await $.pumpWidgetAndSettle(MyApp(position: position));

**Comment by markwigzell** [comment] 2023-02-15 21:32
Update: initially I was using patrol 0.7.2 because that was pulled in by the doc suggested way of "fluter pub add patrol" I believe. But upon revisit I realized that patrol was supposed to be at 1.0..0
Therefore I manually updated it to that. Unfortunately I now have an issue:

**Comment by bartekpacia** [comment] 2023-02-15 21:36
Hi @markwigzell, thanks for reporting this issue. I believe this is a duplicate of #843. Please take a look at it and tell me if you agree.

**Comment by markwigzell** [comment] 2023-02-15 21:49
Hi yes, seems like same bug, except I do have a test file set up. Not sure what I haven't done. As I mentioned in my 2nd comment above, I am hard coding API 33 in the build.gradle, but vm_service is lagging and so flutter pub add modified my patrol dependency to 0.7.2, not 1.0.0

**Comment by bartekpacia** [comment] 2023-02-15 22:06
Sure, I understand.

This set up instructions:

```
flutter pub add patrol --dev
```

indeed does have the problem that the it'll use an older version if there's a dependency conflict.

So, please use 1.0.0, 0.7.2 is kinda ancient and we don't support it. `vm_service` version is hardcoded in the Flutter version, so you likely have to update it. I highly recommend using the newest (3.7).

**Comment by bartekpacia** [comment] 2023-02-15 22:07
Closing as duplicate of #843.

**Comment by bartekpacia** [comment] 2023-02-15 22:08
> except I do have a test file set up

Hmm, interesting.

Have you also completed all the required steps to set up native automation?

**Comment by markwigzell** [comment] 2023-02-15 22:16
Hi, so there is definite issue with vm_service version, because I was hard-coding the API 33 of Android. But as to all required steps: frankly its a little confusing: what are the steps for "native automation"? I must have missed something there. I did not change anything, just added my app_test.dart to the "integration_test" folder. I never tried to do flutter's integration_test since it didn't look like I could use it on permissions.

**Comment by markwigzell** [comment] 2023-02-15 22:22
Btw: I'm currently using flutter 3.8.0-12.0.pre.31 as you can see from the "doctor" output above.

**Comment by bartekpacia** [comment] 2023-02-15 22:37
Hi, sorry about not linking "the instructions" – [they're here](https://patrol.leancode.co/native/setup). I was answering another issue at the same time and forgot to paste the link into this issue.

Sorry again.

**Comment by markwigzell** [comment] 2023-02-15 22:48
ah, np. I'll review and get back to you. I did miss the "patrol" clause in the yaml, and I didn't do the rename of the main activity. I'll get back once I complete those.

**Comment by neiljaywarner** [comment] 2023-02-16 16:25
@bartekpacia  we are getting tests marking as "PASS" even when we have native automation set up but they fail.  i will make a new ticket as we are using flutter 3.7, patrol 1.0 etc.

**Comment by markwigzell** [comment] 2023-02-16 17:27
@bartekpacia I was missing the updates to the "app/build.gradle", so once those were done I now have a working example, thank you. I believe the issue of "always PASS" is that the null case of an incompletely defined test is somehow "succeeding" probably as you mentioned because the process return code is 0 which would be success. @neiljaywarner

**Comment by markwigzell** [comment] 2023-02-16 17:33
Addendum: I recommend changing the documentation to just having the one "Getting Started" section incorporate the Setup into it, and have it handle both IOS and Android in the same "Getting Started" section. Also, delay introducing the actual test code until all necessary steps have been sequentially outlined. Isolate the optional parts clearly so the flow is not broken. Because of the back and forth nature of how the set up is documented, I actually ended up missing some essential aspect of Setup.

**Comment by bartekpacia** [comment] 2023-02-16 18:15
Great to hear that this issue is resolved, and thank you for the feedback on the documentation 🙏🏻  I created #948 to track this.

**Closed by bartekpacia** 2023-02-16 18:15 UTC

**Comment by jeremiahlukus** [comment] 2023-02-17 13:01
@bartekpacia  maybe related:

After passing the webview auth page and loading the flutter page I am doing some basic checks however these expects always pass 

```
        final findera = find.byType(PaginatedSongsListView);
        expect(findera, findsOneWidget); // should pass
        expect(findera, findsNothing);  // should fail 
```

Using the patrol syntax 

```
        expect($(SearchBar), findsOneWidget); // should pass
        expect($(SearchBar), findsNothing); //should fail
```

I am always getting 

```
PASS  app_test.dart on iPhone 14
```

**Comment by jeremiahlukus** [comment] 2023-02-17 13:05
```
void main() {
  patrolTest(
    'counter state is the same after going to home and switching apps',
    ($) async {
      main_dart.main();
      for (var i = 0; i < 300; i++) {
        await $.pump();
      }

      await $(#signInButtonKey).tap();
      for (var i = 0; i < 300; i++) {
        await $.pump();
      }
      await $.native.enterTextByIndex(
        'test@hey.com',
        index: 0,
      );
      await $.native.enterTextByIndex(
        'testing',
        index: 1,
      );

      await $.native.tap(Selector(text: 'Sign in'));

      for (var i = 0; i < 300; i++) {
        await $.pump();
      }
     
      expect($(SearchBar), findsOneWidget);
      expect($(SearchBar), findsNothing); // fails here but doesn't tell xcodebuild

      await $(#signOutButtonKey).tap(); // does not get executed due to above failure 
      for (var i = 0; i < 300; i++) {
        await $.pump();
      }
    },
    nativeAutomation: true,
  );
}
```
