### ISSUE TITLE
patrol test command fails :compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by matanyos** [leancodepl/patrol#2150] opened 2024-03-12 13:10 UTC
### Steps to reproduce

add mobile_scanner: ^4.0.0 package from pub dev in your flutter project, and try to run 'patrol test' command

note: building and running flutter app on the same machine 'flutter run' command works fine

### Actual results

this is the results i get running patrol test command 

• Building apk with entrypoint test_bundle.dart...

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':mobile_scanner:compileDebugJavaWithJavac'.
        > error: invalid source release: 17

        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.

        * Get more help at https://help.gradle.org

        BUILD FAILED in 54s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (55.7s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:265:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:199:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:341:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:285:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#9      main (file:///C:/Users/matan/AppData/Local/Pub/Cache/hosted/pub.dev/patrol_cli-2.6.4/bin/main.dart:6:20)
<asynchronous suspension>

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

[3.5.2patrol: ^3.5.2](patrol: ^3.5.2)

### Patrol Doctor output

Patrol doctor:
Patrol CLI version: 2.6.4
Android:
• Program adb found in C:\Users\matan\AppData\Local\Android\Sdk\platform-tools\adb.exe
• Env var $ANDROID_HOME set to C:\Users\matan\AppData\Local\Android\Sdk

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.19045.4046], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.87.1)
[√] Connected device (4 available)
[√] Network resources

**Comment by piotruela** [comment] 2024-03-13 06:42
Hi @matanyos. I wasn't able to reproduce the issue. When I added `mobile_scanner` as the dependency to project, `patrol test` was still executed successfully. Although I found an [issue](https://github.com/juliansteenbakker/mobile_scanner/issues/922) in package repo which might be related to your problem. I'm going to close this issue as this is not a bug in patrol. You can post an example project in which you observed the issue on [patrol discord server](https://discord.gg/ukBK5t4EZg).

**Closed by piotruela** 2024-03-13 06:42 UTC
