### ISSUE TITLE
ASWebAuthenticationSession permission dialog

### ISSUE THREAD

**Issue by wferem1** [leancodepl/patrol#485] opened 2022-10-20 08:02 UTC
I have a flutter app which redirect the user to an SSO page to login. on iOS this starts an `ASWebAuthenticationSession` or `SFAuthenticationSession` (depending on the iOS version) which shows a dialog as follows:
![image](https://user-images.githubusercontent.com/88385151/196891000-80b36429-455a-43e2-9a33-19a9a89d63d1.png)

I tried tapping the `Continue` button, or call `$.native.grantPermissionWhenInUse` to allow the permissions, but it seems that this is not a permission dialog (none is found) and tapping with `Selector(text: 'Continue')` returns with code `NOT_FOUND`.

Is there any way to have the `PatrolTester` approve/cancel this request?

**Comment by bartekpacia** [comment] 2022-10-20 08:48
Hi @wferem1! Thanks for creating the issue :)

You were thinking good to use `$.native.tap(Selector(text: 'Continue'))`. Just one more thing: you need to specify the appId of the app you're interacting with. All system dialogs on iOS are owned by the Springboard app (its bundleID is `com.apple.springboard`).

So try doing this:

```dart
await $.native.tap(
  Selector(text: 'Continue'),
  appId: 'com.apple.springboard',
);
```

Let me know if this helped!

I should probably add info to docs about this.

**Comment by wferem1** [comment] 2022-10-20 09:11
Hi @bartekpacia! That indeed did the trick, thanks for explaining!

**Comment by wferem1** [comment] 2022-10-20 10:11
I have another question, i can't seem to enter text in the textfields on the webview shown after i tap continue. 

![bitmap](https://user-images.githubusercontent.com/88385151/196921291-57ee8612-b307-4afe-b5c7-9d49cda96d2b.png)

on Android this worked by calling `$.native.enterText(Selector(text: 'Email address'), 'some-text')` but on iOS this does not seem to work. I tried it with my bundle id, the springboard id and safari's id (com.apple.mobilesafari) but none of them seem to work (nothing is found)

**Comment by bartekpacia** [comment] 2022-10-20 13:05
I don't know the solution to your problem – I haven't encountered this case myself yet 😅

Please try listing all bundle identifiers present on the Simulator:

```console
$ xcrun simctl listapps booted
```

and see if anything looks interesting and try. Unfortunately, there's no better way to find out.

Good luck and let me know if this helped. If not, we'll think of a different solution :)

**Comment by bartekpacia** [comment] 2022-10-20 13:07
Maybe `com.apple.webapp`?

**Comment by bartekpacia** [comment] 2022-10-20 13:10
Also, try using `enterTextByIndex()` instead of `enterText()` – it's a bit more reliable.

So:

```dart
$.native.enterTextByIndex('wferem1@gmail.com', index: 0);
$.native.enterTextByIndex('NyanCar', index: 1);
```

**Comment by Curosevic** [comment] 2022-10-20 16:43
Also facing this issue. I've tried index but I keep getting NOT_FOUND text field at index doesn't exist. And when I try enterText it never seems to find the field.

**Comment by bartekpacia** [comment] 2022-10-20 16:48
Hi @Curosevic, sorry to hear that.

Unfortunately, I don't have a reproducible example on which I could find the right `appID`. It doesn't have to be code – it can be any app (even on the App Store) which is using `ASWebAuthenticationSession` that I could download and play with. I'll be grateful for any suggestions of such apps!

**Comment by Curosevic** [comment] 2022-10-20 18:29
Looks like I was able to get it using enterText  and my apps appId :)

**Comment by bartekpacia** [comment] 2022-10-21 22:56
@wferem1 Let me know if your problem persists.

**Comment by wferem1** [comment] 2022-10-26 06:56
I can't seem to get it working, this is the part of my code starting from the permission dialog
``` dart
 
  if (Platform.isIOS) {
    // extra popup before opening webview
    await tester.native.tap(Selector(text: 'Continue'), appId: 'com.apple.springboard',);

    await tester.native.enterTextByIndex(
      'email@test.com',
      index: 0,
      appId: 'com.apple.webapp', // I tried with and without an appId (safari, webapp, springboard, my own)
    );

    await tester.native.enterTextByIndex(
      'password!',
      index: 1,
      appId: 'com.apple.webapp',
    );

    await tester.native.tap(
      Selector(text: 'Continue'),
    );
  }
```

**Comment by Curosevic** [comment] 2022-10-26 18:27
You could try enterText instead of enterByIndex. EnterByIndex didn't work for me but enterText did.

**Comment by bartekpacia** [comment] 2022-10-26 18:41
I have a hypothesis why `enterTextByIndex()` doesn't work but `enterText()` does.

This is because `enterTextByIndex()`, when called, looks at all the text fields present in the app and attempts to find the text field with the given index, failing if it doesn't exist.

`enterText()`, on the other hand, has a timeout (10s by default), so if a text field is not found immediately (because the website is, for example, loading), it will wait for it and fail only after the timeout has passed.

If you're interested in how it works under the hood, here's Swift code for [enterText()](https://github.com/leancodepl/patrol/blob/master/AutomatorServer/ios/AutomatorServerUITests/Automator.swift#L87-L104), and here for [enterTextByIndex()](https://github.com/leancodepl/patrol/blob/master/AutomatorServer/ios/AutomatorServerUITests/Automator.swift#L106-L131)

**Comment by Yokoi-K** [comment] 2022-10-31 05:10
@bartekpacia 

My app has Google authentication.
https://pub.dev/packages/google_sign_in

I would like to say in advance that my language is Japanese. So it is not in English.

Tapping the iOS dialog during Google Authentication was successful.

However, the email address input in the following Google modal fails.

### iOS native dialog for google_sign_in (Success)

<img src="https://user-images.githubusercontent.com/29598247/198934015-c5ca3e98-0cda-4515-91d4-4b9aacb87232.png" width="300px">


```dart
    await tester.pumpAndSettle();
    
    // This is success.
    await native.tap(
      // '続ける' is 'Continue' Japanese.
      Selector(text: '続ける'),
      appId: 'com.apple.springboard',
    );
```

### email address input for google_sign_in (Failure)

```enterText``` does not work.

<img src="https://user-images.githubusercontent.com/29598247/198935469-f8cae444-df92-4df9-bb17-ad903a0d0ba0.png" width="300px">

```dart
await tester.pumpAndSettle();

    // This is failure
    await native.enterTextByIndex(
      'test@gmail.com',
      index: 0,
      appId: 'com.apple.webapp',
    );

    // or This (also failure)
    await native.enterText(
    //  'メールアドレスまたは電話番号' is 'Email address or phone number' Japanese.
    Selector(text: 'メールアドレスまたは電話番号'),
       appId: 'com.apple.webapp',
       text: 'test@gmail.com',
    );
```

thanks.

**Comment by Yokoi-K** [comment] 2022-11-09 07:29
I was mistaken.

I solved the problem by setting the bundleId of my app properly.

**Comment by bartekpacia** [comment] 2023-01-29 01:57
Closing because it looks like it was resolved  :) Feel free to comment and I'll be happy to continue the discussion :)

**Closed by bartekpacia** 2023-01-29 01:57 UTC
Labels: needs more info, automator: ios
