### ISSUE TITLE
Can't run example code on Android

### ISSUE THREAD

**Issue by llleodeleon** [leancodepl/patrol#1541] opened 2023-07-18 03:24 UTC
### Steps to reproduce

I followed the guide to integrate native testing on my project without success.
I tried running the example to check how the build configuration worked. 
On my project I can run the test command. but the created android test class, regardless if kotlin or java fails with `Unresolved Unresolved reference: PatrolJUnitRunner` among others

The errors on the example are shown below. Any ideas for both problems are welcome. 

### Actual results

The error when I run on the root `❯ patrol test --target integration_test/example_test.dart
`

```
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

No device specified, using the first one (9CDXS1P0F)
• Building apk with entrypoint test_bundle.dart...
        /bin/sh: ./gradlew: No such file or directory
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 127) (6ms)
Exception: Gradle build failed with code 127
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 127
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:230:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:167:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:310:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:254:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:72:20)
<asynchronous suspension>
#9      main (file:///Users/Shared/.pub-cache/hosted/pub.dev/patrol_cli-2.0.4/bin/main.dart:6:20)
<asynchronous suspension>

```

The error when I run on the android folder `❯ patrol test --target ../integration_test/example_test.dart`

```
pubspec.yaml doesn't exist: /Users/Shared/GitHub/patrol/packages/patrol/example/android/pubspec.yaml
FileSystemException: pubspec.yaml doesn't exist, path = '/Users/Shared/GitHub/patrol/packages/patrol/example/android/pubspec.yaml'
#0      PubspecReader.read (package:patrol_cli/src/pubspec_reader.dart:72:7)
#1      TestCommand.run (package:patrol_cli/src/commands/test.dart:86:35)
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#3      CompletionCommandRunner.runCommand (package:cli_completion/src/command_runner/completion_command_runner.dart:81:18)
#4      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:310:30)
<asynchronous suspension>
#5      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:254:18)
<asynchronous suspension>
#6      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:72:20)
<asynchronous suspension>
#7      main (file:///Users/loop/.pub-cache/hosted/pub.dev/patrol_cli-2.0.4/bin/main.dart:6:20)
<asynchronous suspension>

```

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: 2.0.4

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
❯ patrol doctor
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.0.4
Program adb found in /Users/Shared/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/Shared/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 14.0 23A5276g darwin-arm64, locale en-DK)
[!] Android toolchain - //Shared sdk installation
[!] Xcode -  //Xcode Beta
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.0)
[✓] Connected device (1 available)
[✓] Network resources

```

</details>

**Comment by bartekpacia** [comment] 2023-07-18 07:13
Hi @llleodeleon, sorry for the problems.

Re: first problem
Please run `flutter build apk --debug` before running `patrol test` and let me know if this helped

Re:second problem
Duplicate of #743.

**Comment by bartekpacia** [comment] 2023-08-15 12:17
No response, assuming it's solved.

**Closed by bartekpacia** 2023-08-15 12:17 UTC
