### ISSUE TITLE
how to sign in google account in native google sign in dialog

### ISSUE THREAD

**Issue by Origogi** [leancodepl/patrol#1918] opened 2023-11-16 11:10 UTC
### Use case

how to sign in google account in native google sign in dialog

![image](https://github.com/leancodepl/patrol/assets/35194820/ff9168b2-f362-41cb-8b57-eb7b20eb7b13)

Can i get sample code or document??

Select `account` or Select `Use another account` and input id, password

### Proposal

Check Usecase

**Comment by bartekpacia** [comment] 2023-11-16 11:33
related:
- #1786
- #287

**Comment by jBorkowska** [comment] 2023-11-16 11:43
Here's a small sample for choosing account for Android:
`await $.native.tap(
        Selector(
          resourceId: 'com.google.android.gms:id/account_display_name',
          text: 'your username',
        ),
      );`

"Use another account" can be accessed by text or resourceId (if it has one). Sample for process of signing up looks like this (Android as well):

`await automator.enterText(
    Selector(resourceId: 'identifierId'),
    text: 'email',
  );

  await automator.tap(
    Selector(
      resourceId: 'identifierNext',
    ),
  );

  await automator.enterText(
    Selector(resourceId: 'password'),
    text: 'password',
  );

  await automator.tap(
    Selector(
      resourceId: 'passwordNext',
    ),
  );

  await automator.tap(
    Selector(
      resourceId: 'signinconsentNext',
    ),
  );

  await automator.tap(
    Selector(
      resourceId: 'com.google.android.gms:id/sud_items_switch',
    ),
  );

  await automator.tap(Selector(text: 'MORE'));

  await automator.tap(Selector(text: 'ACCEPT'));`
  
  BTW you can find properties of native views in our devtools extension, available in version 3.0 (https://patrol.leancode.co/v3)

**Comment by mateuszwojtczak** [comment] 2023-11-16 15:17
@Origogi I'm closing this issue right now since it's not a bug or feature request. For further discussion, we can continue this on Patrol Discord [here](https://discord.gg/K5hq2Stw)

**Closed by mateuszwojtczak** 2023-11-16 15:17 UTC
