### ISSUE TITLE
App is uninstalled before every test

### ISSUE THREAD

**Issue by bigmikehoncho** [leancodepl/patrol#1866] opened 2023-11-06 18:24 UTC
Thanks for the simplified integration test package!

Apologies for potentially a basic question. I am trying to test my app which has a log in process. I'd like to only run/test this process once and then run all my other tests after the user is already signed in. However, it seems the app is always uninstalled/reinstalled between tests even when I run something like:
```
patrol test \
  --target integration_test/login_test.dart --no-uninstall \
  --target integration_test/logout_test.dart --no-uninstall
```

Or if I `group()` all the tests together in one file starting with the `patrolTest('login', ...)` and then the other tests the same uninstall/reinstall occurs between each patrolTest. I _could_ run the login code at the beginning of every single patrolTest but this seems unnecessary and time consuming when running the tests.

Is it possible I'm doing something wrong here or is there a workaround I'm not aware of?

**Notes:**
patrol cli: 2.2.0
patrol: 2.3.1
App is running on physical Android Pixel 7 device

**Comment by bartekpacia** [comment] 2023-11-06 21:08
Hi @bigmikehoncho, thanks for the kind words :)

This is working as intended - in end-to-end UI testing (which is Patrol's main use case), you want every test to be as hermetic as possible. Patrol does this by calling `pm shell clear <your package name>` (on your Android device) in between every test invocation.
To disable this behavior, remove this line:

```
testInstrumentationRunnerArguments clearPackageData: "true"
```

from the `android/app/build.gradle` file. This is a flag that comes from [Android Test Orchestrator](https://developer.android.com/training/testing/instrumented-tests/androidx-test-libraries/runner#use-android) - Patrol uses it under the hood to achieve this isolation behavior.

**Comment by bigmikehoncho** [comment] 2023-11-07 19:14
@bartekpacia thanks for the suggestions! I can definitely understand the design decision there. We have login + onboarding flow that must be traversed every time, unfortunately, which adds a lot of overhead while trying to write the tests. I guess if I could remove it during development of the tests and then add it back in once development is done, that would be ideal.

Unfortunately even removing that line does not seem to stop it from re-installing 🤔 for me:
```
testInstrumentationRunnerArguments clearPackageData: "true"
```

**Comment by bartekpacia** [comment] 2023-11-08 08:30
That's strange that removing `testInstrumentationRunnerArguments clearPackageData: "true"` doesn't work.

Maybe I misunderstood you – there's 2 parts to it:
- app state is cleared between each test (as in: between every call to `patrolTest()` in your Dart test files). This behavior can be disabled by disabling that `clearPackageData` flag
- the app is uninstalled from the device _before_ and _after_ every call to `patrol test`/`patrol develop`. This behavior can be disabled by passing the `--no-uninstall` flag to Patrol CLI:
  
  ```
  patrol test -t integration_test/my_test.dart --no-uninstall
  ```

Let me know if that helps you.

**Comment by bigmikehoncho** [comment] 2023-11-08 18:01
Ok that makes sense. I probably should've said "clearing the package" (which is what I want to prevent) vs "re-installing".

Anyway, today I re-built/installed the app directly (from Android Studio, not using `patrol test`). And now it seems to be working as expected with `clearPackageData` removed and running:
```
patrol test --target integration_test/logout_test.dart
```

I guess I thought that `patrol test` rebuilt the apk so that would be enough 🤷, but maybe not . Seems to work well now though, thank you!

**Comment by bartekpacia** [comment] 2023-11-08 18:05
> I guess I thought that patrol test rebuilt the apk so that would be enough 🤷

That's true – `patrol test` rebuilds the apk.

anyway happy to hear that. please close the issue if that's all :)

**Closed** 2023-11-08 18:18 UTC
