### ISSUE TITLE
Not able to interact with google place picker which is presented from native iOS side 

### ISSUE THREAD

**Issue by erjayagile** [leancodepl/patrol#1695] opened 2023-09-15 07:33 UTC
### Steps to reproduce

1. Implemented the things as per leancode docs
2. written simple patrol test to check for login flow.
3. tested few permission dialogs such as push notification and location permission for native side interaction and works great 
4. when trying to interact with google place picker it is causing interaction issue from iOS side while its working great for android don't know what went wrong 

### Actual results

While trying to interact with google place picker which is presented from native iOS side internally it is working for android but not working on iOS i have tried $.native.enterText() and $.native.enterTextByIndex() both but no luck for iOS.

Rest of the test works fine as expected flutter side and native side also working perfectly fine suck as permission dialogs etc. 

### Logs

<details>
<summary>Logs</summary>

```
No device specified, using the first one (iPhone 14 Plus)
• Building app with entrypoint test_bundle.dart for iOS simulator (debug)...
✓ Completed building app with entrypoint test_bundle.dart for iOS simulator (60.4s)
• Running app with entrypoint test_bundle.dart for iOS simulator on simulator iPhone 14 Plus...
        2023-09-15 12:36:13.411 xcodebuild[39889:238678] [MT] IDETestOperationsObserverDebug: 41.088 elapsed -- Testing started completed.
        2023-09-15 12:36:13.411 xcodebuild[39889:238678] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
        2023-09-15 12:36:13.411 xcodebuild[39889:238678] [MT] IDETestOperationsObserverDebug: 41.088 sec, +41.088 sec -- end
        Failing tests:
                -[RunnerUITests patrolTest]
        
        ** TEST EXECUTE FAILED **
        
        2023-09-15 12:36:13.532 xcodebuild[39889:238678] [MT] IDEResultKit: Warning: While writing a result bundle to /Users/agile-44/Documents/Git Projects/Flutter Goat Grub Mobile/goat_grub/build/ios_results_1694761531432.xcresult, not all contents have been imported, as the Staging directory still contains the following files/directories: ["1_Test"]
✗ Failed to execute tests of app with entrypoint test_bundle.dart for iOS simulator on simulator iPhone 14 Plus (xcodebuild exited with code 65) (42.1s)
Error: xcodebuild exited with code 65
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.

```

</details>

### Patrol version

patrol: ^2.2.4

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
agile-44@agile-44s-Mac-mini goat_grub % patrol doctor
In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.
      
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.1.3
Program adb found in /Users/agile-44/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.0.1 22A400 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by erjayagile** [comment] 2023-09-15 07:33
@bartekpacia can you please look into this 

Thanks in advance

**Comment by bartekpacia** [comment] 2023-09-15 07:35
Hi,

> 
    Implemented the things as per leancode docs
    written simple patrol test to check for login flow.
    tested few permission dialogs such as push notification and location permission for native side interaction and works great
    when trying to interact with google place picker it is causing interaction issue from iOS side while its working great for android don't know what went wrong

These steps are not reproducible. I cannot clone your repo to see the problem. Please provide reproduction steps or I'll have to close it.

**Comment by erjayagile** [comment] 2023-09-15 07:38
> Hi,
> 
> > 
> 
> ```
> Implemented the things as per leancode docs
> written simple patrol test to check for login flow.
> tested few permission dialogs such as push notification and location permission for native side interaction and works great
> when trying to interact with google place picker it is causing interaction issue from iOS side while its working great for android don't know what went wrong
> ```
> 
> These steps are not reproducible. I cannot clone your repo to see the problem. Please provide reproduction steps or I'll have to close it.

Actually i can not provide repo as it's our company's live project

**Comment by bartekpacia** [comment] 2023-09-15 07:57
Then please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by erjayagile** [comment] 2023-09-15 08:34
@bartekpacia 
Everything works fine but when i am using google_places_picker library then user interaction to enter text of search field is not being i have tried both ways 

await tester.native.enterTextByIndex('Cin', inde
![Simulator Screen Shot - iPhone 14 Plus - 2023-09-12 at 15 23 30](https://github.com/leancodepl/patrol/assets/145102219/db713632-5998-4c97-ba7c-aef953c82345)
x: 0);
and 
await tester.native.enterText(Selector(text: 'Search'), text: 'Cin');

attaching the screenshot of the place picker

**Comment by bartekpacia** [comment] 2023-09-15 08:45
Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so I can `git clone` your code and debug it.

**Comment by erjayagile** [comment] 2023-09-15 08:52
@bartekpacia We can not share those things if any other things may i help to reproduce the issue then please let me know

**Comment by bartekpacia** [comment] 2023-09-15 08:54
Please create a new, minimal project that demonstrates this problem.

**Comment by erjayagile** [comment] 2023-09-15 08:56
Problem is so simple just add google_places_picker this library to your any of the existing demo and then try to enter text on the search field of the place picker on iOS simulator from  patrol's native side function it will not perform any results

**Comment by bartekpacia** [comment] 2023-09-15 09:21
As I said, create minimal repro so I can quickly investigate it. Please respect the rules which you agreed to when creating the issue.

**Comment by erjayagile** [comment] 2023-09-15 09:24
@bartekpacia 
Yes sure will share the things required once created a minimal quick demo so you can quick check, give me some time to create that demo

**Comment by bartekpacia** [comment] 2023-09-15 09:24
Thank you :)

**Comment by bartekpacia** [comment] 2023-10-26 18:37
Closing because no [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) was provided.

Feel free to open a new issue with all the required information provided.

**Closed by bartekpacia** 2023-10-26 18:37 UTC
