### ISSUE TITLE
Android - An unexpected packet was received before the handshake

### ISSUE THREAD

**Issue by Bazni** [leancodepl/patrol#2071] opened 2024-01-26 09:07 UTC
### Steps to reproduce

I set patrol on my project and ran it on my Android phone.
`patrol test -d f8f10384 -t integration_test/example_test.dart`

### Actual results

I got stuck on the 3rd step.
```
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (8.1s)
• Executing tests of apk with entrypoint test_bundle.dart on device f8f10384...
```

Then nothing happens. If I add the verbose params to get more logs, I got `[DDMLIB]: An unexpected packet was received before the handshake.`

### Logs

Logs
https://pastebin.com/3AeurLcg

### Patrol version

  patrol: ^3.4.0
  patrol_cli v2.6.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.6.1
Android:
• Program adb found in /Users/gwendalbazin/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/gwendalbazin/Library/Android/sdk
iOS / macOS:
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.2.1 23C71 darwin-arm64, locale en-FR)
    • Flutter version 3.16.2 on channel stable at /Users/gwendalbazin/fvm/versions/3.16.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (8 weeks ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/gwendalbazin/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • ANDROID_HOME = /Users/gwendalbazin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (5 available)
    • ONEPLUS A5010 (mobile)              • f8f10384                                 • android-arm64  • Android 10 (API 29)
    • iPhone (mobile)                     • 00008110-000451C41152801E                • ios            • iOS 17.2.1 21C66
    • Gwendal’s iPad (mobile)             • fd46f10d8b64a947e2122abb145ccb115d134562 • ios            • iOS 17.2 21C62
    • iPhone SE (3rd generation) (mobile) • 52BFBA29-5537-4BF5-9DEE-34391B1265D2     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • Chrome (web)                        • chrome                                   • web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by piotruela** [comment] 2024-02-05 06:56
Hi, @Bazni. Thanks for opening the issue. Were you able to reproduce this issue in a empty flutter project? If yes, please share this project with us so we can take a look. This is most likely a setup issue specific to your project and not a bug in flutter so I'll close this ticket. Feel free to join the [discord channel](https://discord.gg/ukBK5t4EZg) and describe your issue there.

**Closed by piotruela** 2024-02-05 06:56 UTC

**Comment by Bazni** [comment] 2024-02-05 21:48
Thanks for your response, I created an issue here because nobody responded on discord.
I supposed it is a problem in the conf, but I have no clue why it doesn't work.
