### ISSUE TITLE
Taking photo with camera is flaky

### ISSUE THREAD

**Issue by mateuszwojtczak** [leancodepl/patrol#1033] opened 2023-03-03 13:02 UTC
Customer: @KmlBaranowski 

Please provide more information on this.

**Comment by KmlBaranowski** [comment] 2023-03-06 14:17
Sometimes (2/5 testruns), when taking a picture with camera, the test fails randomly in process described as Open camera app -> take photo with main shoot button -> use taken photo for application.

**Comment by KmlBaranowski** [comment] 2023-03-06 14:20
Lines executing the process are:

`const shootPhotoButton = 'com.sec.android.app.camera:id/normal_center_button';
await $.native.grantPermissionWhenInUse();
await $.native.tap(
  Selector(
    resourceId: shootPhotoButton,
    ),
  );
await $.native.tap(Selector(textContains: 'OK')); //Confirm taken photo`

**Comment by bartekpacia** [comment] 2023-03-06 14:26
Can you show the output of `flutter logs` running alongside your tests?

**Comment by KmlBaranowski** [comment] 2023-03-07 12:09
Cannot provide valid logs as the issue cannot be reproduced on Patrol 1.0.1 with CLI 1.0.5, current rate 0/30

**Comment by bartekpacia** [comment] 2023-03-25 21:22
Closing since not longer reproducible.

**Closed by bartekpacia** 2023-03-25 21:22 UTC
Labels: bug, package: patrol
