### ISSUE TITLE
Unable to tap button using Selector during microsoftonline log in process

### ISSUE THREAD

**Issue by PeterBriggsGreggs** [leancodepl/patrol#1194] opened 2023-04-12 15:49 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/leancodepl/patrol/issues)

### Steps to reproduce

Created PatrolTest for logging into Android app using Active Directory log in process.
Shop code entered via app.
Microsoft Online account email created
Password entered 
Microsoft Stay signed in? dialog box is displayed but unable to find or press any button or check box. 

```dart
patrolTest('Check login works with valid store number',
        config: patrolConfig, nativeAutomatorConfig: nativeAutomatorConfig, nativeAutomation: true, (PatrolTester $) async {
      await initialiseStorage();
      await $.pumpWidgetAndSettle(const ProviderScope(child: MyApp()));
      // When
      await $.tester.shortToMediumPause();
      await $.tester.enterKeypadNumber('0043');
      await $.tester.clickNumberKeypadNextButton();
      await $.tester.shortToMediumPause();

      await $.native.enterTextByIndex('WxxxxDxxxxSxxxx13', index: 0);
      await $.native.tap(Selector(text: 'Sign in'));
      await $.native.pressBack();
      await $.native.enterTextByIndex('WxxxxDxxxxSxxxx13', index: 0);
      await $.native.tap(Selector(text: 'Sign in'));
      await $.native.pressBack();
      await $.native.enterTextByIndex('WxxxxDxxxxSxxxx13', index: 0);
      await $.native.tap(Selector(text: 'Sign in'));
      await $.native.tap(Selector(text: 'Yes'));

      await $.tester.doNotFindShopLoginConfirmationButtons();
    });
```

### Actual results

The test purposely signs in 3 times to try and prove there is reliable interaction between PatrolTest and the sign in dialog boxes as well as using other native features like pressBack().

In the test when the line below is commented out the test passes, but when this line is uncommented the test fails:
      await $.native.tap(Selector(text: 'Yes'));

The attached video runs the test twice. First run of the test, this test passes as the above line is commented out. The second run of the test fails as the Selector does not find the 'Yes' button.

[PeterBriggsSelectorFailsv01.txt](https://github.com/leancodepl/patrol/files/11213276/PeterBriggsSelectorFailsv01.txt)
[Video0.webm](https://user-images.githubusercontent.com/86053215/231509583-e026b7ad-61f1-43a4-95f2-5c6715c20834.webm)

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>
[PeterBriggsSelectorFailsv01-verbose.txt](https://github.com/leancodepl/patrol/files/11213340/PeterBriggsSelectorFailsv01-verbose.txt)

### Patrol version

patrol: ^1.0.8
patrol_CLI 1.1.3

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-peterbriggs@Peters-MBP-2 gotg_apps_grecords % patrol doctor
Patrol CLI version: 1.1.3
Program adb found in /Users/peterbriggs/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/peterbriggs/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /usr/local/bin/ideviceinstaller
Program ios-deploy found in /usr/local/bin/ios-deploy
>
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- peterbriggs@Peters-MBP-2 gotg_apps_grecords % fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-x64, locale en-GB)
    • Flutter version 3.7.7 on channel stable at /Users/peterbriggs/fvm/versions/3.7.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (5 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    • Android SDK at /Users/peterbriggs/Library/Android/sdk
    • Platform android-33, build-tools 34.0.0-rc2
    • ANDROID_HOME = /Users/peterbriggs/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
 -->
```

</details>

**Comment by bartekpacia** [comment] 2023-04-13 11:49
Hi, thanks for creating this issue, and sorry for the problems.

I can't really help you since the reproduction steps provided _aren't reproduction steps_ – meaning, I can't just `git clone` your repo and run it on my machine to debug it. If you can't share the whole project (which you probably can't - totally understandable), then create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) instead.

**Comment by bartekpacia** [comment] 2023-04-13 12:04
Closing to not clutter the issues.

**Comment by PeterBriggsGreggs** [comment] 2023-04-14 07:41
Hi @bartekpacia,
Thanks for your reply. I'm in the process of getting a small subset of our application which covers the problem running in a separate project & repo for you to investigate further.
Do you want me to open a new issue when I have the repo ready for you ??
Thanks

**Comment by bartekpacia** [comment] 2023-04-14 09:52
Thanks a lot for preparing the example repo - that is always of great help.

I reopened this issue, you can simply edit it with the new info :)

**Comment by PeterBriggsGreggs** [comment] 2023-04-14 10:35
Will load the example repo on Monday (17APR23).

**Comment by PeterBriggsGreggs** [comment] 2023-04-17 14:19
Hi @bartekpacia,
The link below is a link to my repository which contains an example app for you to run debug on.
https://github.com/PeterBriggsGreggs/sign-in-example-v01/tree/main/sign_in_example

Please note that the example in this repo does not find the Microsoft password field either by the   enterTextByIndex  or using the  enterText with a Selector. Whilst this is not exactly the same as the error in the video I attached to this call. I think it is very similar and if you are able to fix this issue I think it could also help with fixing the problem with tapping the  Yes   button on the Stay signed in?  dialog.

Please tell me if you have any problems or if you need me to do anything else.
Thank you for your help and support.
Kind regards

**Comment by PeterBriggsGreggs** [comment] 2023-04-25 09:50
Hi @bartekpacia,
Just a quick follow up to ask whether you and the team have been able to investigate this issue further as yet ?
Thanks

**Comment by bartekpacia** [comment] 2023-04-25 09:55
Hi Peter, unfortunately I haven't yet had time to do it. I'm currently focusing on pushing a [new 10x feature](#1004). After it's done, we plan to focus on bug bashing and overall stability :)

**Comment by PeterBriggsGreggs** [comment] 2023-04-25 10:02
OK... Thanks for the update

**Comment by jBorkowska** [comment] 2023-07-12 12:18
Might be a duplicate of #1159

**Comment by bartekpacia** [comment] 2023-07-20 09:00
> The link below is a link to my repository which contains an example app for you to run debug on.
https://github.com/PeterBriggsGreggs/sign-in-example-v01/tree/main/sign_in_example

This repository doesn't exist.

**Comment by bartekpacia** [comment] 2023-09-13 08:08
Closing - lack of response.

**Closed by bartekpacia** 2023-09-13 08:08 UTC
Labels: bug, package: patrol, a: native automation
