### ISSUE TITLE
bs_android macOs Failed to open/read local data from file/application

### ISSUE THREAD

**Issue by RuslikMer** [leancodepl/patrol#1689] opened 2023-09-14 10:11 UTC
### Steps to reproduce

use macOs
run bs_android

### Actual results

rus@MacBook-Pro flapster % bs_android                 
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (13.7s)
curl: (26) Failed to open/read local data from file/application

issue is that inside bs_android you used ' ' instead of " "
curl -F 'file=somefile'  it will not work on macOs
curl -F "file=somefile" it works

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

^2.2.3

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.
      
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.1.3
Program adb found in /Users/rus/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/rus/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
✓] Flutter (Channel stable, 3.13.2, on macOS 13.4 22F66 darwin-arm64, locale ru-TR)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ Android SDK file not found: /Users/rus/Library/Android/sdk/platforms/android-34/android.jar.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] Connected device (2 available)            
[✓] Network resources
```

</details>

**Comment by RuslikMer** [comment] 2023-09-14 10:14
zsh 5.9 (x86_64-apple-darwin22.0)

GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.5.0)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by bartekpacia** [comment] 2023-09-15 07:21
> issue is that inside bs_android you used ' ' instead of " "
curl -F 'file=somefile' it will not work on macOs
curl -F "file=somefile" it works

That script uses `bash`, not `zsh`. What's your bash version?

**Comment by RuslikMer** [comment] 2023-09-18 04:40
> zsh 5.9 (x86_64-apple-darwin22.0)
> 
> GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.5.0) Copyright (C) 2022 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
> 
> This is free software; you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.

already shared

**Comment by RuslikMer** [comment] 2023-09-18 06:51
<img width="783" alt="Снимок экрана 2023-09-18 в 13 49 27" src="https://github.com/leancodepl/patrol/assets/30290012/99155c9c-9526-4452-bf66-561a4d0b6f12">
what I did wrong? may be u can provide correct instruction please

**Comment by RuslikMer** [comment] 2023-09-18 07:11
<img width="576" alt="Снимок экрана 2023-09-18 в 14 09 24" src="https://github.com/leancodepl/patrol/assets/30290012/1296844c-425a-4c2f-a3a4-234d2c7fbfd5">
it does not work under bash too

**Comment by bartekpacia** [comment] 2023-09-28 09:14
Your APK is probably generated in a different location than the one `bs_android` looks in. This is likely caused by your usage of flavors.

Please run:

```
brew uninstall mobile-tools
brew update
brew install mobile-tools
```

The new version of `bs_android` has improved error messages that should help you debug it.

**Comment by RuslikMer** [comment] 2023-09-29 05:48
I used this to setup project https://patrol.leancode.co/getting-started, and only one flavor --staging , but that script asked path  build/app/outputs/apk/debug/app-debug.apk
 not matched with this documentation , looks like that it should search in build/app/outputs/apk/androidTest/debug/app-debug.apk 
<img width="855" alt="Снимок экрана 2023-09-29 в 12 41 01" src="https://github.com/leancodepl/patrol/assets/30290012/15e227ba-027e-45c5-9c9d-563e006b6b72">
so problem no only in flavor --staging

**Comment by RuslikMer** [comment] 2023-09-29 05:53
and also I can not remove staging flavor because it will build production version and I have this error
	FAILURE: Build failed with an exception.
	
	* What went wrong:
	Execution failed for task ':app:processProductionDebugGoogleServices'.
	> No matching client found for package name 'com.bambinifashion.production'

**Comment by bartekpacia** [comment] 2023-09-29 08:08
> how I can customize it to work correct with staging flavor 

`bs_android --flavor staging`

**Comment by bartekpacia** [comment] 2023-09-29 18:08
Closing since it's not a problem with Patrol, but with the supporting tooling - https://github.com/leancodepl/mobile-tools.

**Comment by bartekpacia** [comment] 2023-09-29 18:09
Gonna keep it unlocked until you confirm the issue is solved @RuslikMer

**Closed by bartekpacia** 2023-09-29 18:08 UTC

**Comment by RuslikMer** [comment] 2023-10-02 05:47
bash-5.2$ bs_android --flavor staging
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (10.8s)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  238M    0   243  100  238M      4  4838k  0:00:50  0:00:50 --:--:--    63
/Users/rus/homebrew/bin/bs_android: line 80: jq: command not found

**Comment by bartekpacia** [comment] 2023-10-02 06:16
You need to install `jq`: `brew install jq`.

**Comment by RuslikMer** [comment] 2023-10-02 07:42
thanks now this script works

**Comment by bartekpacia** [comment] 2023-10-02 08:24
happy to hear that
