### ISSUE TITLE
Patrol CLI doesn't always use platform-native path separators

### ISSUE THREAD

**Issue by piotruela** [leancodepl/patrol#1980] opened 2023-12-04 12:59 UTC
For now, we'are using unix-styled path separators in `patrol_cli` code. We should use platform-native path separators. Some work has been done [here](https://github.com/leancodepl/patrol/pull/1315).

**Comment by jBorkowska** [comment] 2024-08-01 12:56
Also mentioned in #1256

**Comment by jBorkowska** [comment] 2024-08-05 11:51
Size: S (need to check if still occurs)

**Comment by jBorkowska** [comment] 2024-08-05 11:52
Closing as duplicate of #1256

**Closed as completed by jBorkowska** 2024-08-05 11:52 UTC
Labels: package: patrol_cli, tech debt, P2
