### ISSUE TITLE
BUG: Compilation errors in patrol finders

### ISSUE THREAD

**Issue by lorena-cimpean-wolf** [leancodepl/patrol#2173] opened 2024-04-04 05:36 UTC
### Use case

I tried submitting this as a bug but for some reason even though I filled in all the required fields with the logs the submit button is still disabled. Please have a look at that.

The issue I actually want to report is that the following compilation errors are thrown on test run:

     ../../../.pub-cache/hosted/pub.dev/patrol_finders-2.0.2/lib/src/custom_finders/patrol_tester.dart:148:28: Error: Too many positional arguments: 1 allowed, but 3 found.
        Try removing the extra positional arguments.
            await tester.pumpWidget(widget, duration, phase);
                                   ^
        ../../../.pub-cache/hosted/pub.dev/patrol_finders-2.0.2/lib/src/custom_finders/patrol_tester.dart:208:28: Error: Too many positional arguments: 1 allowed, but 3 found.
        Try removing the extra positional arguments.
            await tester.pumpWidget(widget, duration, phase);
                                   ^
        Target kernel_snapshot failed: Exception
        
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':app:compileFlutterBuildDebug'.
        > Process 'command '/opt/homebrew/Caskroom/flutter/3.7.11/flutter/bin/flutter'' finished with non-zero exit value 1
        
Please have a look at the method signature from integration test. It looks like it might have changed at some point.
 
**Method signature in flutter test:**
  
Future<void> pumpWidget(
    Widget widget, {
    Duration? duration,
    EnginePhase phase = EnginePhase.sendSemanticsUpdate,
    bool wrapWithView = true,
  })

Patrol finder pump method:
 /// See [WidgetTester.pumpWidget].
  Future<void> pumpWidget(
    Widget widget, [
    Duration? duration,
    EnginePhase phase = EnginePhase.sendSemanticsUpdate,
  ]) async {
    **Update this to use named params: **
    await tester.pumpWidget(widget, duration, phase);
  }

### Proposal

<details>
<summary>Logs</summary>

```
 Building apk with entrypoint test_bundle.dart...
        ../../../.pub-cache/hosted/pub.dev/patrol_finders-2.0.2/lib/src/custom_finders/patrol_tester.dart:148:28: Error: Too many positional arguments: 1 allowed, but 3 found.
        Try removing the extra positional arguments.
            await tester.pumpWidget(widget, duration, phase);
                                   ^
        ../../../.pub-cache/hosted/pub.dev/patrol_finders-2.0.2/lib/src/custom_finders/patrol_tester.dart:208:28: Error: Too many positional arguments: 1 allowed, but 3 found.
        Try removing the extra positional arguments.
            await tester.pumpWidget(widget, duration, phase);
                                   ^
        Target kernel_snapshot failed: Exception
        
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':app:compileFlutterBuildDebug'.
        > Process 'command '/opt/homebrew/Caskroom/flutter/3.7.11/flutter/bin/flutter'' finished with non-zero exit value 1
        
        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        
        * Get more help at https://help.gradle.org
        
        BUILD FAILED in 11s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (12.0s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:279:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:213:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:347:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:291:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#9      main (file:///.../.pub-cache/hosted/pub.dev/patrol_cli-2.7.0/bin/main.dart:6:20)
<asynchronous suspension>


```

</details>

patrol: ^3.6.1

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.7.0
Flutter command: flutter 
  Flutter 3.19.0-13.0.pre.3 • channel master
Android: 
• Program adb found in ...Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to ...Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller

```

</details>

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel master, 3.19.0-13.0.pre.3, on macOS 14.3 23D56 darwin-arm64, locale en-RO)
    • Flutter version 3.19.0-13.0.pre.3 on channel master at /opt/homebrew/Caskroom/flutter/3.7.11/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 44ce0bf956 (9 weeks ago), 2024-01-29 04:31:07 -0500
    • Engine revision 1405cb7b6e
    • Dart version 3.4.0 (build 3.4.0-82.0.dev)
    • DevTools version 2.31.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at .../Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9065

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 14.3 23D56 darwin-arm64
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 123.0.6312.106

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by piotruela** [comment] 2024-04-04 13:52
Looks to me as a duplicate of [this issue](https://github.com/leancodepl/patrol/issues/2170) therefore closing this as one.

**Closed by piotruela** 2024-04-04 13:52 UTC
