### ISSUE TITLE
The installed app does not automatically get deleted

### ISSUE THREAD

**Issue by ckxddd0324** [leancodepl/patrol#2218] opened 2024-06-10 20:30 UTC
### Steps to reproduce

1. Run the test
2. Test Passed
3. Simulator is closed but not deleted
4. Rerun the same
5. Installethe app/replace example one

### Actual results

I would expect the app got automatically deleted when the test is finished

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

3.7.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.7.0
Flutter command: flutter 
  Flutter 3.19.0 • channel stable
Android: 
• Program adb found in /Users/ss/library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/ss/library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.4 23E214 darwin-arm64, locale en-US)
    • Flutter version 3.19.0 on channel stable at /Users/ss/DevTools/flutter_3_19
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (4 months ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/a820757/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • ANDROID_HOME = /Users/ss/library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2024.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code copy.app/Contents
    • Flutter extension version 3.90.0

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code_intel.app/Contents
    • Flutter extension version 3.90.0
```

</details>

**Comment by jBorkowska** [comment] 2024-06-11 09:28
Hi @ckxddd0324 !
By default, `patrol_cli` uninstalls the app from the device, unless you pass a flag `--no-uninstall` to a patrol command. I couldn't reproduce this issue. Please provide more details: 
- which OS are you on?
- what kind of device you're using to run the test (real/simulated, iOS/Android/Mac)?
- which exact command are you running (`patrol test` or `patrol develop`)?

Also, logs from a test run would be useful for us (please use --verbose flag, so we can see if patrol attempted to uninstall the app).

**Comment by ckxddd0324** [comment] 2024-06-11 13:54
Hi @jBorkowska 
- I m on Mac
- I am trying to run my test on simulated iOS
- I m using `patrol test`
cmd - ` patrol test -t integration_test/example_test.dart -d 3EA2A341-673C-4066-A3A1-339D3B62EFD7`
I m setting to run on iOS for now so attaching the device id. And when I run the cmd, it built the app, start the simulator then install the app. And since it is running the same device all the time, I see that the app was not deleted

**Comment by ckxddd0324** [comment] 2024-06-11 20:44
I kind of figure out the issue, but what is the correct way to run the test with specific iOS version. It seems like when I use `-d {device_id}` for iOS, it does not use that specific emulator. It would try to use the latest version of iOS version with that device type.

**Comment by jBorkowska** [comment] 2024-06-12 10:55
What do you mean by "it does not use that specific emulator"? What happens instead? Which simulator is used?

In general, there are issues with the latest Xcode and running patrol tests on simulators with older iOS versions than latest, more info here: https://github.com/leancodepl/patrol/issues/2003

**Comment by ckxddd0324** [comment] 2024-06-12 16:24
I guess it is similar issue with the thread you shared. I was trying to use `-d {device_id}` but patrol is running the 17.5/the latest iOS version with the same device type on my machine instead of running the run on specific device that I added to `-d`

**Comment by jBorkowska** [comment] 2024-06-13 10:09
This looks like what I sent then. There is a workaround for this issue in the comments, take a look at it. For now I'm closing the issue, feel free to reopen or create new one if there will be some more problems

**Closed by jBorkowska** 2024-06-13 10:09 UTC
