### ISSUE TITLE
Failed to build app with entrypoint test_bundle.dart for iOS simulator

### ISSUE THREAD

**Issue by Bazni** [leancodepl/patrol#2073] opened 2024-01-29 08:42 UTC
### Steps to reproduce

1. Setup by following the documentation
2. Create the first example of the documentation
3. Run it with patrol test --verbose -d 52BFBA29-5537-4BF5-9DEE-34391B1265D2 -t integration_test/example_test.dart

### Actual results

`Failed to build app with entrypoint test_bundle.dart for iOS simulator (xcodebuild exited with code 65)` 

I got `Error: xcodebuild exited with code 65`. I thought it was related to my certificate but I don't have any error on Testflight.

When I tried to run it on a real device I got `Error: Running on physical iOS devices is possible only in release mode`. 

Where can I choose to run my app in release mode in patrol conf?
EDIT: With the flag `--release` it runs in release mode and with this flag, I got the same error  
`Failed to build app with entrypoint test_bundle.dart for iOS device (xcodebuild exited with code 65)`.

### Logs

<details>
<summary>Real device logs</summary>

```
Verbose mode enabled. More logs will be printed.
$ flutter --suppress-analytics --no-version-check pub deps --style=list
Received 1 test target(s)
Received test target: /Users/gwendalbazin/Documents/Kpler/mobile-app/kpler_app/integration_test/example_test.dart
Generated entrypoint /Users/gwendalbazin/Documents/Kpler/mobile-app/kpler_app/integration_test/test_bundle.dart with 1 bundled test(s)
$ flutter --no-version-check --suppress-analytics devices --machine
Received 1 device(s) to run on
Received device: Gwendal’s iPad
Received 9 --dart-define(s) (0 custom, 9 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=com.kpler2022.mobile
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.kpler2022.mobile
Received internal --dart-define: PATROL_ANDROID_APP_NAME=kpler_app
Received internal --dart-define: PATROL_IOS_APP_NAME=kpler_app
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
Received internal --dart-define: PATROL_TEST_SERVER_PORT=8081
Received internal --dart-define: PATROL_APP_SERVER_PORT=8082
• Building app with entrypoint test_bundle.dart for iOS device (release)...
$ flutter build ios --no-version-check --suppress-analytics --config-only --no-codesign --release --target /Users/gwendalbazin/Documents/Kpler/mobile-app/kpler_app/integration_test/test_bundle.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_APP_PACKAGE_NAME=com.kpler2022.mobile --dart-define PATROL_APP_BUNDLE_ID=com.kpler2022.mobile --dart-define PATROL_ANDROID_APP_NAME=kpler_app --dart-define PATROL_IOS_APP_NAME=kpler_app --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false --dart-define PATROL_TEST_LABEL_ENABLED=true --dart-define PATROL_TEST_SERVER_PORT=8081 --dart-define PATROL_APP_SERVER_PORT=8082
	Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
	Building com.kpler2022.mobile for device (ios-release)...
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos -destination generic/platform=iOS -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
	error: the following command failed with exit code 1 but produced no further output
	Run custom shell script 'Run Script'
	** TEST BUILD FAILED **
	
✗ Failed to build app with entrypoint test_bundle.dart for iOS device (xcodebuild exited with code 65) (8.3s)
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:136:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:76:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:265:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:199:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:341:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:285:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#10     main (file:///Users/gwendalbazin/.pub-cache/hosted/pub.dev/patrol_cli-2.6.1/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:136:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:76:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:265:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:199:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:341:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:285:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#10     main (file:///Users/gwendalbazin/.pub-cache/hosted/pub.dev/patrol_cli-2.6.1/bin/main.dart:6:20)
<asynchronous suspension>

```
</details>

<details>
<summary>Simulator logs</summary>

```
Verbose mode enabled. More logs will be printed.
$ flutter --suppress-analytics --no-version-check pub deps --style=list
Received 1 test target(s)
Received test target: /Users/gwendalbazin/Documents/Kpler/mobile-app/kpler_app/integration_test/example_test.dart
Generated entrypoint /Users/gwendalbazin/Documents/Kpler/mobile-app/kpler_app/integration_test/test_bundle.dart with 1 bundled test(s)
$ flutter --no-version-check --suppress-analytics devices --machine
Received 1 device(s) to run on
Received device: iPhone SE (3rd generation)
Received 9 --dart-define(s) (0 custom, 9 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=com.kpler2022.mobile
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.kpler2022.mobile
Received internal --dart-define: PATROL_ANDROID_APP_NAME=kpler_app
Received internal --dart-define: PATROL_IOS_APP_NAME=kpler_app
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
Received internal --dart-define: PATROL_TEST_SERVER_PORT=8081
Received internal --dart-define: PATROL_APP_SERVER_PORT=8082
• Building app with entrypoint test_bundle.dart for iOS simulator (debug)...
$ flutter build ios --no-version-check --suppress-analytics --config-only --no-codesign --debug --simulator --target /Users/gwendalbazin/Documents/Kpler/mobile-app/kpler_app/integration_test/test_bundle.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_APP_PACKAGE_NAME=com.kpler2022.mobile --dart-define PATROL_APP_BUNDLE_ID=com.kpler2022.mobile --dart-define PATROL_ANDROID_APP_NAME=kpler_app --dart-define PATROL_IOS_APP_NAME=kpler_app --dart-define INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false --dart-define PATROL_TEST_LABEL_ENABLED=true --dart-define PATROL_TEST_SERVER_PORT=8081 --dart-define PATROL_APP_SERVER_PORT=8082
	Building com.kpler2022.mobile.dev for simulator (ios)...
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme Runner -configuration Debug -sdk iphonesimulator -destination generic/platform=iOS Simulator -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
	error: the following command failed with exit code 1 but produced no further output
	Run custom shell script 'Run Script'
	** TEST BUILD FAILED **
	
✗ Failed to build app with entrypoint test_bundle.dart for iOS simulator (xcodebuild exited with code 65) (9.3s)
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:136:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:76:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:265:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:199:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:341:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:285:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#10     main (file:///Users/gwendalbazin/.pub-cache/hosted/pub.dev/patrol_cli-2.6.1/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Error: xcodebuild exited with code 65
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.build.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:136:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#3      IOSTestBackend.build (package:patrol_cli/src/ios/ios_test_backend.dart:76:5)
<asynchronous suspension>
#4      TestCommand._build (package:patrol_cli/src/commands/test.dart:265:7)
<asynchronous suspension>
#5      TestCommand.run (package:patrol_cli/src/commands/test.dart:199:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:341:18)
<asynchronous suspension>
#8      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:285:18)
<asynchronous suspension>
#9      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#10     main (file:///Users/gwendalbazin/.pub-cache/hosted/pub.dev/patrol_cli-2.6.1/bin/main.dart:6:20)
<asynchronous suspension>
```

</details>

### Patrol version

patrol: ^3.4.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.6.1
Android: 
• Program adb found in /Users/gwendalbazin/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/gwendalbazin/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```

[✓] Flutter (Channel stable, 3.16.2, on macOS 14.2.1 23C71 darwin-arm64, locale en-FR)
    • Flutter version 3.16.2 on channel stable at /Users/gwendalbazin/fvm/versions/3.16.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (9 weeks ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/gwendalbazin/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • ANDROID_HOME = /Users/gwendalbazin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • iPhone (mobile)                     • 00008110-000451C41152801E                • ios            • iOS 17.2.1 21C66
    • Gwendal’s iPad (mobile)             • fd46f10d8b64a947e2122abb145ccb115d134562 • ios            • iOS 17.2 21C62
    • iPhone SE (3rd generation) (mobile) • 52BFBA29-5537-4BF5-9DEE-34391B1265D2     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • Chrome (web)                        • chrome                                   • web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by piotruela** [comment] 2024-02-05 07:00
Hi @Bazni. This also looks like a setup issue to me so closing it for now. If you'll decide to describe the issue on discord channel, please take a look at [#rules](https://discord.com/channels/1167030497612922931/1167076660370214954) where you can find an instruction of how to provide a logs which will help us better understand the cause of the issue.

**Closed by piotruela** 2024-02-05 07:00 UTC
