### ISSUE TITLE
Support for '--dart-define-from-file' via Command Line

### ISSUE THREAD

**Issue by Bwolfs2** [leancodepl/patrol#2196] opened 2024-05-16 13:26 UTC
I'm currently using the Flutter Patrol package and have encountered an issue. The package does not support the '--dart-define-from-file' option via the command line. This feature is crucial for my project's workflow, and I'm wondering if there are any plans to implement this functionality.

Could you please let me know if this feature is on the roadmap, and if so, when we might expect it to be available in the package? Any information or guidance you can provide would be greatly appreciated.

[Old PR Add dart defines from file](https://github.com/leancodepl/patrol/pull/1477)

**Comment by bartekpacia** [comment] 2024-05-21 18:54
Why is it crucial for your project? What is possible with `--dart-define-from-file` that is not possible with `--dart-define`?

**Comment by Bwolfs2** [comment] 2024-05-21 19:13
It works, but we have 24 variables and, for now, 5 whitelabels. Sometimes, the variables are changed and not the Test variables. If we have the --dart-define-from-file option, we can use the same files for whitelabels and for testing. We currently have 5 whitelabels, but we will be adding more.

**Comment by jBorkowska** [comment] 2024-06-18 11:26
Closing as duplicate of https://github.com/leancodepl/patrol/issues/1742

**Closed by jBorkowska** 2024-06-18 11:26 UTC
