### ISSUE TITLE
Test is marked with a green "PASS" even when a test fails

### ISSUE THREAD

**Issue by vijaya-sakhamuri** [leancodepl/patrol#1310] opened 2023-05-23 20:42 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/leancodepl/patrol/issues)

### Steps to reproduce

1. run test -  patrol test lib/main_staging.dart --target=integration_test/patrol/patrol_signup_location_test.dart --flavor production --dart-define TESTING_ENVIRONMENT=stage --verbose
2. Test fails

----------test------
patrolTest('resident app signup with location integration test', config: patrolConfig, nativeAutomation: true,
      ($) async {
   .....
    await bootstrap(environment: environment);
    await $.pumpAndSettle();
    await patrolVerifySignupLocationFlow($, testData.orgName2, TestDataClient().env);
    .....
}

---------Config-------
import 'package:patrol/patrol.dart';

const patrolConfig = PatrolTesterConfig();

const nativeAutomatorConfig = NativeAutomatorConfig(
  packageName: 'com.mobile.resident',
  bundleId: 'com.mobile.resident',
);

### Actual results

Patrol returns incorrect result (PASS) for failed tests

<img width="882" alt="Screen Shot 2023-05-23 at 11 53 21 AM" src="https://github.com/leancodepl/patrol/assets/37450484/2631b88a-7ff3-4d96-afd6-df43c7ac24ae">
<img width="990" alt="Screen Shot 2023-05-23 at 11 57 49 AM" src="https://github.com/leancodepl/patrol/assets/37450484/1d1f2411-e4cc-4991-817c-2fe0df54a1b7">

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>
[patrolLogs.txt](https://github.com/leancodepl/patrol/files/11548115/patrolLogs.txt)

### Patrol version

patrol: ^1.1.4

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Patrol CLI version: 1.1.10
Program adb found in /opt/homebrew/bin/adb
Env var $ANDROID_HOME set to /Users/vijaya.sakhamuri/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
Program ios-deploy found in /opt/homebrew/bin/ios-deploy! -->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 12.6.5 21G531 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
! -->
```

</details>

**Comment by bartekpacia** [comment] 2023-05-23 21:02
Hi @vijaya-sakhamuri, this issue does not contain enough info for me to reproduce it. Please create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that I can clone and run to see the exact problem you're seeing.

Sorry, but we have many issues and must prioritize the well-described ones.

**Comment by bartekpacia** [comment] 2023-05-23 21:32
Duplicate of #1309

**Closed** 2023-05-23 21:32 UTC
