### ISSUE TITLE
When triggering Hot Restart for the first time after the test starts, the user has to click enter

### ISSUE THREAD

**Issue by jBorkowska** [leancodepl/patrol#1065] opened 2023-03-09 14:46 UTC
Steps to reproduce:
1. Run `patrol develop -t <test file>
2. Wait for message that hot restart is ready
3. Press `r`

Nothing happens until user presses enter. Occurs only first time per test run.

**Comment by bartekpacia** [comment] 2023-03-09 14:57
Cannot reproduce it on macOS :( Maybe it's windows specific? 

Did you encounter this while testing `customer: budowa`? Which test was that?

**Comment by jBorkowska** [comment] 2023-03-16 13:32
Check on WIndows, it's happening every time to me.

**Comment by bartekpacia** [comment] 2023-03-22 10:15
I don't have access to a Windows machine.

**Comment by bartekpacia** [comment] 2023-06-01 17:44
Action item: run some example app tests on Windows with Hot Restart.

If it works, let's close this issue.

**Comment by bartekpacia** [comment] 2023-07-21 07:54
I think this is a duplicate of #1365, which was fixed in #1377.

**Comment by bartekpacia** [comment] 2023-09-11 11:28
No response - closing.

**Closed by bartekpacia** 2023-09-11 11:28 UTC
Labels: bug, package: patrol_cli
