### ISSUE TITLE
`patrol test` run tests in alphabetical order not in order they are ordered against --target

### ISSUE THREAD

**Issue by findms** [leancodepl/patrol#1467] opened 2023-07-05 11:03 UTC
### Steps to reproduce

Make sure you have multiple tests under integration_test package and some outside as well. For Example:
-integration_test
----A_test.dart
----B_test.dart
----C_test.dart
----D_test.dart

Now if you run your tests in any different order like below:
patrol test \
  --target integration_test/C_test.dart \
  --target integration_test/A_test.dart \
  --target integration_test/D_test.dart \
  --target integration_test/B_test.dart \

It will run in alphabetical order like A_test.dart>B_test.dart>C_test.dart>D_test.dart

### Actual results

Tests running in alphabetical order rather than they are ordered to run in --target

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

1.1.11

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Program adb found in /Users/manish.singh/Library/Android/sdk//platform-tools//adb
Env var $ANDROID_HOME set to /Users/manish.singh/Library/Android/sdk/
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
Program ios-deploy found in /opt/homebrew/bin/ios-deploy
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.4.1 22F82 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

</details>

**Comment by fylyppo** [comment] 2023-07-05 11:19
Hi, it's the way it works now, so it's not a bug. But subjectively I like this idea. Out of curiosity, what are the use cases in your mind?

**Comment by findmanish** [comment] 2023-07-05 12:35
@fylyppo Thank for the info. The idea is that Not necessaily the test name should be according to the flow. Fir example. lets say there are 2 tests AddIteam and CreateUser so as per my requirement I should be running CreateUser first and then AddItem but according to patrol it will run AddItem and CreateUser due to alphabetical order. Unless if I put 1 at the start of CreateUser i,e 1_CreateUser and 2_AddItem. Haven't checked this if this will work or not but the order in which tests ahs been added as target should be followed. Thanks

**Comment by fylyppo** [comment] 2023-07-05 13:11
@findmanish I had some test cases like you mentioned, I resolved them by creating one big test like E2E starting with creating user, then doing some actions on this account and ending with logging out this user.
I did it because I don't want to run "AddItem" test if my previous test "CreateUser" failed, because it's redundant - it'll always fail.
So creating E2E test in those cases is very good approach here IMHO. So I would say tests should be independent from each other. It's much easier to analyze them if they fail. You don't need to think which test caused failure of another test.

TBH I don't see any use cases standing for running tests in a special order XD. So I need to withdraw from my previous opinion that I like this idea, sorry XD

**Comment by findmanish** [comment] 2023-07-06 09:13
@fylyppo Make sense..Thank you

**Comment by bartekpacia** [comment] 2023-07-06 18:08
@fylyppo I think this is a valid issue and should be kept open until we fix it

**Comment by fylyppo** [comment] 2023-07-06 18:11
@bartekpacia Ok then

**Comment by jBorkowska** [comment] 2024-01-12 13:58
Closing, as it is not a valid issue right now

**Closed** 2024-01-12 13:57 UTC
Labels: feature, package: patrol_cli
