### ISSUE TITLE
Unable to give access to photo library

### ISSUE THREAD

**Issue by csondi10** [leancodepl/patrol#1994] opened 2023-12-06 14:29 UTC
### Steps to reproduce

Device: iPhone 15 Pro simulator with iOS 17.0

Goal is to be able to give permission to photo library. I try to tap on "Allow Full Access" button on the native dialog (see attached image).
I use the `image_picker` package to pick photos with the source of `ImageSource.gallery`. This package implicitly requests permission if needed.

I tried the [suggestion](https://github.com/leancodepl/patrol/discussions/1944#discussioncomment-7683593) of @bartekpacia but had no luck.

![284981268-3723a93c-2621-42f5-a125-33e320fe6546](https://github.com/leancodepl/patrol/assets/105285564/4cabffed-e3a6-4a32-9866-fea41da53366)

### Actual results

Basically nothing happened, when I ran
```
await $.native.tap(
  Selector(text: 'Allow full access'),
  appId: io.Platform.isIOS ? 'com.apple.mobileslideshow' : null,
);
```

the button was not tapped and the test eventually failed after a while.
Edit: it also didn't work with the selector text of Allow Full Access

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: 3.0.3

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.3.1+1
Program adb found in /Users/**/Library/Android/sdk//platform-tools/adb
Env var $ANDROID_HOME set to /Users/**/Library/Android/sdk/
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale hu-HU)
    • Flutter version 3.16.0 on channel stable at /Users/csondi/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (3 weeks ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/**/Library/Android/sdk/
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/**/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • iPhone 15 Pro (mobile) • 75D7BE3B-EAEA-4E32-A8DE-6F4BA51B3719 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 119.0.6045.199
    ! Error: Browsing on the local area network for Iphone12. Ensure the device is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jpohhhh** [comment] 2023-12-09 15:02
Random drive-by comment, I was searching for a different issue: any chance it's 'Allow full access' in your code versus 'Allow Full Access' on the button?

**Comment by bartekpacia** [comment] 2023-12-09 16:36
@jpohhhh Good catch! It's definitely worth trying.

**Comment by jBorkowska** [comment] 2023-12-11 17:01
Hi @csondi10, did you try to inspect this view with our devtools extension? Maybe you'll find the right properties of this button there

**Comment by csondi10** [comment] 2023-12-13 12:09
Hi!
Thanks for your answer. Yes I tried it and I didn't see anything useful. There were a bunch of "other" and basically that's all 😕

**Comment by bartekpacia** [comment] 2023-12-14 13:17
The cause of this problem is that: the permission dialog does not "belong" to `'com.apple.mobileslideshow'`, but to `com.apple.springboard` (the launcher app).

**Comment by abhiche** [comment] 2024-01-30 07:37
> The cause of this problem is that: the permission dialog does not "belong" to `com.apple.mobileslideshow`, but to `com.apple.springboard` (the launcher app).
> 
> Modified version of the example by @csondi10 that should work:
> 
> ```dart
> import 'dart:io' as io;
> 
> // ...
> 
> await $.native.tap(
>   Selector(text: 'Allow Full Access'), // remember about uppercase and lowercase!
>   appId: io.Platform.isIOS ? 'com.apple.springboard' : null,
> );
> ```

This works! Thanks. 
As the next step, I need to select an image from the gallery.
I am clueless right now. Any solution for this?

**Comment by sobimor** [comment] 2024-02-06 10:11
> > The cause of this problem is that: the permission dialog does not "belong" to `com.apple.mobileslideshow`, but to `com.apple.springboard` (the launcher app).
> > Modified version of the example by @csondi10 that should work:
> > ```dart
> > import 'dart:io' as io;
> > 
> > // ...
> > 
> > await $.native.tap(
> >   Selector(text: 'Allow Full Access'), // remember about uppercase and lowercase!
> >   appId: io.Platform.isIOS ? 'com.apple.springboard' : null,
> > );
> > ```
> 
> This works! Thanks. As the next step, I need to select an image from the iOS gallery. I am clueless right now. Any solution for this?

https://stackoverflow.com/a/76601773/5985849

**Comment by jBorkowska** [comment] 2024-02-07 16:19
Closing as solved, reply below is the solution

> The cause of this problem is that: the permission dialog does not "belong" to `com.apple.mobileslideshow`, but to `com.apple.springboard` (the launcher app).
> 
> Modified version of the example by @csondi10 that should work:
> 
> ```dart
> import 'dart:io' as io;
> 
> // ...
> 
> await $.native.tap(
>   Selector(text: 'Allow Full Access'), // remember about uppercase and lowercase!
>   appId: io.Platform.isIOS ? 'com.apple.springboard' : null,
> );
> ```

**Closed by jBorkowska** 2024-02-07 16:19 UTC
Labels: bug, package: patrol, platform: ios, P1
