### ISSUE TITLE
.tap() throws pumpandSettle timedout when this tap navigating to webview. Tap works fine although

### ISSUE THREAD

**Issue by findms** [leancodepl/patrol#1332] opened 2023-06-05 07:17 UTC
### Steps to reproduce

In out app, login is being peformed on webview but before that webview page we ask user to tap on a button(in native) as soon as my code tap on it  - Tap works fine and user navigated to webview to enter credentials but after 20 seconds(my default timeout) it throws exception.

Platform: iOS

### Actual results

![image](https://github.com/leancodepl/patrol/assets/31733022/af63ac4d-bbbb-41c1-8b0b-57b048968f4e)

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

1.1.11

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Verbose mode enabled. More logs will be printed.
Patrol CLI version: 1.1.11
Program adb found in /Users/---------/Library/Android/sdk//platform-tools//adb
Env var $ANDROID_HOME set to /Users/-----/Library/Android/sdk/
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
Program ios-deploy found in /opt/homebrew/bin/ios-deploy
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```

[✓] Flutter (Channel stable, 3.7.7, on macOS 13.4 22F66 darwin-arm64, locale en-DE)
    • Flutter version 3.7.7 on channel stable at /Users/------------/flutterSetup/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd62c0 (3 months ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/------------/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/---------/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 143422b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Users/--------/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) •  • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by bartekpacia** [comment] 2023-06-22 15:03
Hi @findmanish. If you're getting `pumpAndSettle timed out` error, then this means that your application is constantly requesting new frames from the Flutter Engine. This often happens when some animation is constantly running, which prevents `pumpAndSettle()` from returning.


It's hard to help you since you didn't provide a minimal, reproducible example.

**Comment by bartekpacia** [comment] 2023-09-14 09:19
Since this issue is old and has no new activity, I'm going to close it. Please create a new issue if you experience a similar problem.

**Closed by bartekpacia** 2023-09-14 09:19 UTC
