### ISSUE TITLE
Test results aren't very useful when there is more than one exception causing a test failure

### ISSUE THREAD

**Issue by BSoD38** [leancodepl/patrol#1997] opened 2023-12-08 09:39 UTC
### Use case

When a test fails because of an exception, the exception is displayed inside the HTML file.

This is good, but when there is more than one exception, only the message `Multiple exceptions (x) were detected during the running of the current test, and at least one was unexpected.` is displayed, which isn't very useful for debugging.

### Proposal

It would be better to display the whole exception stack inside the HTML file, so it can be more efficiently used for debugging.

**Comment by jBorkowska** [comment] 2023-12-14 13:14
Closing as a duplicate of https://github.com/leancodepl/patrol/issues/951

**Closed** 2023-12-14 13:14 UTC
