### ISSUE TITLE
connectedAndroidTest launched via gradle doesn't complete - Firebase Test Lab Fails

### ISSUE THREAD

**Issue by valtbarbos** [leancodepl/patrol#2283] opened 2024-07-29 17:09 UTC
### Steps to reproduce

Hello, folks.

We are experiencing issues running tests on the Firebase Test Lab. We can reproduce this by running the tests locally with `gradlew app:connectedAndroidTest` in the example project of the patrol package.

0 - It is possible to reproduce this with the example project.
1 - The tests run successfully locally via `patrol test` or even with `flutter drive`.
2 - The tests may, in some scenarios, start execution but never finish (at least within the maximum timeout of Firebase Test Labs, 45 minutes).
3 - If we ONLY rollback the `testInstrumentationRunner` and `MainActivityTest` to the default framework values, everything works as expected (for tests that only use WidgetTester).

The `PatrolJUnitRunner` would be my starting point for investigating the issue, but I need more information, tips, or even an example of how to debug the `PatrolJUnitRunner` in this scenario with `gradlew app:connectedAndroidTest`.

I have also upgraded all dependencies in my project, including Android, Flutter, etc.; the logs look beautiful without warnings or errors, but the problem persists.

Here is an example of using `gradlew app:connectedAndroidTest`: https://github.com/flutter/flutter/tree/main/packages/integration_test#firebase-test-lab

```bash
pushd android
flutter build apk --flavor dev --no-tree-shake-icons && \
./gradlew app:assembleAndroidTest && \
./gradlew app:assembleDebug -Ptarget=../integration_test/example_test.dart && \
./gradlew app:connectedAndroidTest -Ptarget=../example/integration_test/example_test.dart
popd
```

### Actual results

connectedAndroidTest launched via gradle doesn't complete

### Logs

<details>
<summary>Logs</summary>

```
connectedAndroidTest launched via gradle doesn't complete
```

</details>

### Patrol version

latest

### Patrol Doctor output

Patrol doctor:
Patrol CLI version: 3.0.1
Flutter command: flutter 
  Flutter 3.22.3 • channel stable
Android: 
• Program adb found in /Users/alvertabbaros/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/alvertabbaros/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /usr/local/bin/ideviceinstaller

**Comment by piotruela** [comment] 2024-07-30 06:06
Hi @valtbarbos. The way you try to run the tests is not correct for how Patrol works. If you want to recreate everything that Patrol does when you execute `patrol test` command, you can add `--verbose` flag to see more logs (and all internally run commands). But if you're trying to run patrol tests on FTL there is an easier way. Take a look at [this page](https://patrol.leancode.co/ci/firebase-test-lab) in our docs.
Closing this as it is not a bug. If you'll have any more questions feel free to ask them on [discord channel](https://discord.com/invite/ukBK5t4EZg).

**Closed by piotruela** 2024-07-30 06:06 UTC
