### ISSUE TITLE
Patrol's Example App does not build on device (real device & simulator) in Flutter

### ISSUE THREAD

**Issue by alperefesahin** [leancodepl/patrol#1960] opened 2023-11-28 14:09 UTC
### Steps to reproduce

` patrol test --target integration_test/example_test.dart`
or
` patrol debug --target integration_test/example_test.dart`

### Actual results

After setting up the env. (iOS&android setup, project setup) for Flutter, I expect that the app can be built, but it throws some logs in the console and finishes the console task. The project does not matter, there should be the Material app and scaffold. I wanted to start with the example app and then implement the real application, but faced with that issue.
You can see the logs, below.

Also, I use the 2.2.2 version for CLI, since,  `final binding = PatrolBinding.ensureInitialized(NativeAutomatorConfig());` part gives an error for the 2.3.2 version (I saw this solution in the issues).

### Logs

<details>
<summary>Logs</summary>

```
In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.
      

Update available! 2.2.2 → 2.3.1+1
Run patrol update to update

No device specified, using the first one (emulator-5554)
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (30.8s)
• Executing tests of apk with entrypoint test_bundle.dart on emulator-5554...
✓ Completed executing apk with entrypoint test_bundle.dart on emulator-5554 (16.0s)

```

</details>

### Patrol version

patrol: ^2.3.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Program adb found in /Users/***/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/***/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 14.0 23A344 darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by piotruela** [comment] 2023-11-28 14:28
Hi @alperefesahin. It seems to be more of a setup issue than a bug in the repository, so for now, I'll close it. Feel free to join the patrol channel on Discord and describe your issue there. We'll try to help. If you could share the repository with the project where the error occurred it would make it easier for us to find the cause of the issue.
Link to the discord channel: https://discord.gg/ukBK5t4EZg

**Closed by piotruela** 2023-11-28 14:28 UTC

**Comment by alperefesahin** [comment] 2023-11-30 09:48
With the help of @piotruela we solved the problem.

The problem was about the package name in the `MainActivityTest.java` **file**, and the **folder structure** where `MainActivityTest.java` exists. 

Upgrade flutter to the latest version, use the latest version of the patrol, fix the folder structure, package name in the file, and `pubspec.yaml` file. The example app is working as expected.

Thanks!
