### ISSUE TITLE
Getting - SocketExpection, when NativeAutomator and interacting with Native elements

### ISSUE THREAD

**Issue by iam-kj** [leancodepl/patrol#2126] opened 2024-02-23 11:25 UTC
### Steps to reproduce

**Dart Version :  2.19.X**

1. We are using Dart version 2.19.X, doesn't support the Full implementation of Patrol Test as we run our test using "No-Souch_Null_Safety" flag in Flutter Test Command, So had taken up the partial implementation within our Flutter Integration Test.
2. Inside TestWidget we are initialising widget tester as usual but before launching app we will typecast widget tester to patrol integration tester.. please refer pic
3. Please refer to the below snapshot, which has complete test script which is used for testing along with its outcome on Terminal
![Screenshot 2024-02-23 at 4 16 47 PM](https://github.com/leancodepl/patrol/assets/108999289/b149cd04-faea-432d-aac5-edea4eec11db)
4. Pubspec.YAML variables - FYI : we are using 

![Screenshot 2024-02-23 at 4 18 32 PM](https://github.com/leancodepl/patrol/assets/108999289/6299b55e-e58c-4232-91e0-0c6197750c3b)

**Patrol : 2.3.2, Patrol_CLI : 2.2.2 as per the compatibility table from the Patrol blog.**

### Actual results

1. we are getting SocketException while interacting with Native elements on Android Emulator, which can be seen in below snapshot. otherwise interaction with Application elements all works fine.!!!

![Screenshot 2024-02-23 at 4 30 34 PM](https://github.com/leancodepl/patrol/assets/108999289/1828d88c-5b51-44a7-a180-7318febee6ee)

### Logs

<details>
<summary>Logs</summary>

```
[patrol_logs.txt](https://github.com/leancodepl/patrol/files/14384632/patrol_logs.txt)
```

</details>

### Patrol version

Patrol : 2.3.2
Patrol_CLI : 2.2.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
![Screenshot 2024-02-23 at 4 46 01 PM](https://github.com/leancodepl/patrol/assets/108999289/6e2c20c6-76a8-444b-a725-70eef49a5873)
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
![Screenshot 2024-02-23 at 4 45 46 PM](https://github.com/leancodepl/patrol/assets/108999289/aad03590-23a4-477b-80ba-904d77081b2b)
```

</details>

**Comment by Meghana-hv** [comment] 2024-02-23 11:29
Patrol and Patrol CLI Compatibility Table 
<img width="740" alt="Screenshot 2024-02-23 at 4 52 13 PM" src="https://github.com/leancodepl/patrol/assets/109101522/ef82c457-275a-4d9e-b72f-eee5bfb926a2">
@bartekpacia @iam-kj

**Comment by bartekpacia** [comment] 2024-02-24 13:05
please don't ping me, I no longer work on Patrol

**Comment by piotruela** [comment] 2024-02-25 21:44
Hi @iam-kj, can you please provide a reproducible example of this issue? Would be much easier to track it down. Although, it looks like it might be related to the incompatibility of the versions.

**Comment by Meghana-hv** [comment] 2024-03-01 13:26
We have created a demo flutter project which matches  with our actual project only difference will be in our actual project we use no sound null safe libraries here in demo project this criteria is not applicable.

Demo flutter project integrated with patrol Integration Test is available in this link
https://drive.google.com/file/d/1xrRLg1EKuVp9zHzX-CEOK8o1NWpSaMaU/view?usp=sharing

FYR.

@piotruela , this is the reproducible example u asked for.
@bartekpacia

**Comment by iam-kj** [comment] 2024-03-04 05:08
we had provided the complete E2E information about the issue, reproducible steps & the codebase as well. Can we get to know what sort of information missing or we failed to respond it back?

We strongly disagree with "Without additional information, we can't resolve this issue. We're therefore reluctantly going to close it." we need precise response from whoever closed this issue.

@piotruela @bartekpacia

**Comment by piotruela** [comment] 2024-03-07 07:49
Hi @iam-kj, sorry for the late reply. Issue was closed by github bot while it should not. Thanks for the reproducible example, I'll take a look at it soon

**Comment by piotruela** [comment] 2024-03-08 07:37
I tried to reproduce the issue with the example project provided by @Meghana-hv but it works for me on Android. Please give some additional information on how to reproduce the problem

**Comment by Meghana-hv** [comment] 2024-03-11 04:17
Hi @piotruela , seems you have executed test using "patrol test" command. Can you give a try executing test using "flutter test" command??

1.  Our Actual project is running with command :  "flutter test integration_test/dummy_test.dart --flavor qa --dartdefine=environment=qa --dart-define=listenForOtp=false --no-sound-null-safety -d emulator-5554"  

2.  Since Patrol test doesn't support no-sound-null-safety tag, if I replace the existing command with patrol test we get error message like "Could not find an option named "no-sound-null-safety". please refer screen shot
<img width="1071" alt="Screenshot 2024-03-11 at 09 37 40" src="https://github.com/leancodepl/patrol/assets/109101522/4cb83835-c76c-4f37-81eb-d0bf16716f9e">

3. Can we get an alternative solution to interact with native element using patrol test/ flutter test which supports all flags present within this command: "flutter test integration_test/dummy_test.dart --flavor qa --dartdefine=environment=qa --dart-define=listenForOtp=false --no-sound-null-safety -d emulator-5554"

**Comment by piotruela** [comment] 2024-03-11 07:19
Ok, I get it. So I'm afraid it will not work. It's not possible to interact with native feature without running `patrol test` command. And `patrol test` indeed does not support `--no-sound-null-safety` flag. I don't think this will ever be supported tbh.

**Closed** 2024-03-15 08:01 UTC
Labels: waiting for response
