### ISSUE TITLE
Getting no test targets to run

### ISSUE THREAD

**Issue by akagupta9** [leancodepl/patrol#794] opened 2023-01-19 12:59 UTC
I am getting -

Bad state: no test targets to run
#0      FlutterTestRunner.run (package:patrol_cli/src/features/drive/flutter_test_runner.dart:105:7)
#1      DriveCommand.execute (package:patrol_cli/src/features/drive/drive_command.dart:310:39)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#3      PatrolCommandRunner.runCommand (package:patrol_cli/src/command_runner.dart:291:18)
<asynchronous suspension>
#4      PatrolCommandRunner.run (package:patrol_cli/src/command_runner.dart:235:18)
<asynchronous suspension>
#5      patrolCommandRunner (package:patrol_cli/src/command_runner.dart:52:14)
<asynchronous suspension>

**Comment by bartekpacia** [comment] 2023-01-19 13:08
Duplicate of https://github.com/leancodepl/patrol/discussions/795

**Closed by bartekpacia** 2023-01-19 13:08 UTC
