### ISSUE TITLE
Make `patrol test` output more readable

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#870] opened 2023-02-03 16:19 UTC
## Problem

Currently, console output of `patrol test` looks like this:

```
$ patrol test
No device specified, using the first one (Barteks-iPhone)
• Building app with entrypoint notifications_test.dart for device...
✓ Completed building app with entrypoint notifications_test.dart for device (51.4s)
• Executing tests of app with entrypoint notifications_test.dart on device Barteks-iPhone...
✓ Completed executing tests of app with entrypoint notifications_test.dart on device Barteks-iPhone (57.9s)
• Building app with entrypoint app_test.dart for device...
✓ Completed building app with entrypoint app_test.dart for device (21.37s)
• Executing tests of app with entrypoint app_test.dart on device Barteks-iPhone...
✓ Completed executing tests of app with entrypoint app_test.dart on device Barteks-iPhone (42s)
```

It gets barely readable once there are more tests. That's what this issue is for.

## Suggested solution

We should improve the log output to be easier to quickly parse by a human.

```
$ patrol test
No device specified, using the first one (Barteks-iPhone)
=> notifications_test.dart on Barteks-iPhone
==> • Building apps
==> ✓ Completed building apps (20s)
==> • Executing tests
==> ✓ Completed executing tests (20s)
=> app_test.dart on Barteks-iPhone
==> • Building apps
==> ✓ Completed building apps (17s)
==> • Executing tests
==> ✓ Completed executing tests (24s)
```

Another idea ("Docker-like"), implying splitting "running tests" into 4 phases:

```
$ patrol test
No device specified, using the first one (Barteks-iPhone)
=> notifications_test.dart on Barteks-iPhone
==> BUILD (21.37s)
==> INSTALL (4s)
==> EXECUTE  app
==> UNINSTALL (0.7s)
```

### Problems

- What should the output look like when running tests simultaneously on many devices?

See also:
- https://github.com/leancodepl/patrol/discussions/528

**Comment by bartekpacia** [comment] 2023-02-05 00:35
Other CLI tools that have great terminal output:
- [Gradle](https://github.com/gradle/gradle)
- [GoReleaser](https://github.com/goreleaser/goreleaser)

**Comment by mateuszwojtczak** [comment] 2023-02-06 12:15
I think we should seek for test runner output experience and not just some CLI output experience. Thus, `spec` example was really great, we should present the effects of the test run. IMO phases like installing or preparing the device are irrelevant as long as they don't fail.

**Comment by proximilian** [comment] 2023-02-16 12:34
Guys, I saw that e.g. Allure test report tool doesn't support dart. Do we have some other tools or runners that can be bound with Patrol for test results output or we only can use the CLI output like we all know? Could you suggest something according to your experience? btw the `spec` example is good.

**Comment by bartekpacia** [comment] 2023-02-16 12:38
Hi @proximilian, I see that [Allure supports JUnit 4](https://docs.qameta.io/allure/#_junit_4), which is used on Android.

If you use Patrol with the native automation feature (i.e you're using the `patrol test` command), you can get the test reports in JUnit XML format just like you'd do in a plain Android app. See also #883.

If you're not using native automation feature (i.e you're using `flutter test` or `spec`), you can use the https://pub.dev/packages/junitreport package to convert results from these tools into JUnit XML format, which is popular and widely supported.

**Comment by jBorkowska** [comment] 2023-11-20 17:07
Closing as duplicate of #561

**Closed by jBorkowska** 2023-11-20 17:07 UTC
Labels: feature, package: patrol_cli
