### ISSUE TITLE
Better Patrol CLI test runner status prompt

### ISSUE THREAD

**Issue by adrian-moisa** [leancodepl/patrol#1855] opened 2023-11-03 22:55 UTC
> Note by @bartekpacia **to all future readers**.
>
> Please see discussion #528 which explains this feature request in more detail.

### Use case

Would be nice to see a live report in terminal of which tests are run and their success state. Without any other logs around.

### Proposal

For example react jest had a nice report of the progression trough the tests. Would be nice to have something similar in patrol as well. I guess it would help also during deployments to see how far along the testing step of the pipeline has progressed. Most deployment tools have an option to inspect the terminal of the current build step. 

<img width="969" alt="image" src="https://github.com/leancodepl/patrol/assets/11160141/7da3d944-3a8b-41b4-9a8d-415081c194ea">

In the current version of patrol all i see is just the finish message or a link to the error log. The -verbose flag contains a lot of information, way more than I need and it's not the one about the tests. Good for debugging patrol itself but not the tests.

<img width="685" alt="image" src="https://github.com/leancodepl/patrol/assets/11160141/87f2c425-4f59-4a14-9aec-1c1cacadd751">

Even nicer would be on the long run to have a dedicated test runner GUI similar to Cypress, snapshots and timetravel would a wet dream. Now I'm not entirely sure how this would be done considering how the emulator works. I guess it could be done via an auxiliary web page that renders the log and the snapshots. I don't see how it could be correlated with the emulator directly.

![banner-cc2e25979d647636d6f991a73e7b940c](https://github.com/leancodepl/patrol/assets/11160141/c38ee744-cd1d-4d90-b2b8-8ef9dd23eebb)

**Edit**: I see there's also open discussion on this topic here: https://github.com/leancodepl/patrol/discussions/528

**Comment by bartekpacia** [comment] 2023-11-05 22:49
Hi @adrian-moisa, thanks a lot for chiming in :) I agree Patrol would really benefit from better real-time logs. I [have an idea](https://github.com/leancodepl/patrol/discussions/528#discussioncomment-6737246) on how this feature could be implemented - but it's pretty low on our priority list tbh.

I think this issue is somewhat a duplicate of the #528 discussion you found.

**Comment by bartekpacia** [comment] 2023-11-08 08:16
I'm gonna label this as feature request and keep it open. We don't really look at Discussions as much as at Issues.

**To all future readers**: please see discussion #528 which has

**Comment by bartekpacia** [comment] 2023-11-20 14:30
There are 2 parts to it:
- showing status of tests (PASSED/FAILED)
- showing steps in individual test ("tapping on X", "entering text XYZ into A", etc.)

We want to do both.

**Comment by jBorkowska** [comment] 2023-11-20 17:23
Let's consider this issue as "showing steps in individual test ("tapping on X", "entering text XYZ into A", etc.)" as @bartekpacia wrote. For showing status of tests there is this issue: #561

**Closed** 2024-12-05 14:20 UTC
Labels: feature, package: patrol, package: patrol_cli, P1
