### ISSUE TITLE
Patrol tests not working in browserstack

### ISSUE THREAD

**Issue by RuslikMer** [leancodepl/patrol#1752] opened 2023-09-29 07:41 UTC
### Steps to reproduce

// My test_bundle.dart

Future<void> main() async {
  test('patrol_test_explorer', () {
    final topLevelGroup = Invoker.current!.liveTest.groups.first;
    final dartTestGroup = createDartTestGroup(topLevelGroup);
    testExplorationCompleter.complete(dartTestGroup);
  });

  // START: GENERATED TEST GROUPS
  group('add_and_remove_from_wishlist_page_test', add_and_remove_from_wishlist_page_test.main);
  group('add_to_wishlist_from_listing_auth_test', add_to_wishlist_from_listing_auth_test.main);
  group('add_to_wishlist_from_listing_test', add_to_wishlist_from_listing_test.main);
  group('add_to_wishlist_from_product_auth_test', add_to_wishlist_from_product_auth_test.main);
  group('add_to_wishlist_from_product_test', add_to_wishlist_from_product_test.main);
  group('brands_live_search_test', brands_live_search_test.main);
  group('categories_live_search_test', categories_live_search_test.main);
  group('check_cross_sale_scroll_product_test', check_cross_sale_scroll_product_test.main);
  group('check_info_tabs_product_test', check_info_tabs_product_test.main);
  group('check_pagination_catalog_test', check_pagination_catalog_test.main);
  group('check_size_guide_product_test', check_size_guide_product_test.main);
  group('fail_order_by_auth_card_test', fail_order_by_auth_card_test.main);
  group('filter_catalog_test', filter_catalog_test.main);
  group('forgot_password_test', forgot_password_test.main);
  group('get_order_by_apple_pay_test', get_order_by_apple_pay_test.main);
  group('get_order_by_auth_card_test', get_order_by_auth_card_test.main);
  group('get_order_by_empty_wallet_test', get_order_by_empty_wallet_test.main);
  group('get_order_by_non_auth_card_test', get_order_by_non_auth_card_test.main);
  group('get_order_by_paypal_test', get_order_by_paypal_test.main);
  group('get_order_with_fixed_amount_voucher_test', get_order_with_fixed_amount_voucher_test.main);
  group('get_order_with_percentage_voucher_test', get_order_with_percentage_voucher_test.main);
  group('go_to_all_products_live_search_test', go_to_all_products_live_search_test.main);
  group('login_before_add_and_remove_from_wishlist_by_listing_test', login_before_add_and_remove_from_wishlist_by_listing_test.main);
  group('patrol_test', patrol_test.main);
  group('products_live_search_test', products_live_search_test.main);
  group('quick_filter_catalog_test', quick_filter_catalog_test.main);
  group('recently_viewed_products_test', recently_viewed_products_test.main);
  group('request_size_product_test', request_size_product_test.main);
  group('sharing_product_test', sharing_product_test.main);
  group('swiping_images_product_test', swiping_images_product_test.main);
  group('swping_images_catalog_test', swping_images_catalog_test.main);
  group('update_user_personal_info_test', update_user_personal_info_test.main);
  // END: GENERATED TEST GROUPS

  final dartTestGroup = await testExplorationCompleter.future;
  final appService = PatrolAppService(topLevelDartTestGroup: dartTestGroup);
  binding.patrolAppService = appService;
  await runAppService(appService);

  await nativeAutomator.markPatrolAppServiceReady();

  await appService.testExecutionCompleted;
}

// [upload app ](https://www.browserstack.com/docs/app-automate/api-reference/flutter/apps#upload-an-app)
curl -u "username:password" -X POST "https://api-cloud.browserstack.com/app-automate/flutter-integration-tests/v2/android/app" -F "file=@build/app/outputs/apk/staging/debug/app-staging-debug.apk"  

// response
{"app_name":"app-staging-debug.apk","app_url":"bs://1277245605f3f03aa256f8427e5e9f7d3c69d426","app_version":"2.1.5","app_id":"1277245605f3f03aa256f8427e5e9f7d3c69d426","uploaded_at":"2023-09-29 06:44:46 UTC","expiry":"2023-10-29 06:44:46 UTC"}%

// [upload test-suite](https://www.browserstack.com/docs/app-automate/api-reference/flutter/tests#upload-a-test-suite)
curl -u "username:password" \
-X POST "https://api-cloud.browserstack.com/app-automate/flutter-integration-tests/v2/android/test-suite" \
-F "file=@build/app/outputs/apk/androidTest/staging/debug/app-staging-debug-androidTest.apk"

// response
{"test_suite_name":"app-staging-debug-androidTest.apk","test_suite_url":"bs://4f83494cc6ef5b0a847534c924fcf7a891e44c37","test_suite_id":"4f83494cc6ef5b0a847534c924fcf7a891e44c37","uploaded_at":"2023-09-29 06:53:59 UTC","expiry":"2023-10-29 06:53:59 UTC","framework":"flutter integration tests"}%

// [execute tests](https://www.browserstack.com/docs/app-automate/api-reference/espresso/builds#execute-a-build)
 curl -u "username:password" \
-X POST "https://api-cloud.browserstack.com/app-automate/flutter-integration-tests/v2/android/build" \     
-d '{"app": "bs://1277245605f3f03aa256f8427e5e9f7d3c69d426", "testSuite": "bs://4f83494cc6ef5b0a847534c924fcf7a891e44c37", "devices": ["Samsung Galaxy S9 Plus-9.0"], "deviceLogs": "true", "networkLogs": "true"}' \                 
-H "Content-Type: application/json"

// response
{"message":"Success","build_id":"f3407b75a87117a3dd213b4c08ce906d633e09f3"}

### Actual results

Browserstack loading several minutes than just show this "Could not start a session : Something went wrong. Please try to run the test again."

Also why did u provide in [instruction](https://patrol.leancode.co/integrations/browserstack) for patrol flutter link to espresso browserstack docs? browserstack has directory special for flutter, or patrol tests somehow working by espresso?

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

v2.1.3

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.1.3
Program adb found in /Users/rus/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/rus/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.4 22F66 darwin-arm64, locale
    ru-TR)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ Android SDK file not found:
      /Users/rus/Library/Android/sdk/platforms/android-34/android.jar.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

**Comment by bartekpacia** [comment] 2023-09-29 18:01
Hi @RuslikMer,

Did you use a special runner as explained in the instruction?

> Also why did u provide in [instruction](https://patrol.leancode.co/integrations/browserstack) for patrol flutter link to espresso browserstack docs?

[Browserstack's support for Flutter](https://www.browserstack.com/docs/app-automate/flutter/getting-started) is dependent on the [`integration_test` plugin](https://github.com/flutter/flutter/tree/master/packages/integration_test), which [has many problems](https://leancode.co/blog/patrol-2-0-improved-flutter-ui-testing).

Among other things, Patrol is a revamped, rewritten version of the `integration_test` plugin. Patrol tests are visible to the native test framework as a normal test - that's why you need to use [Espresso](https://www.browserstack.com/docs/app-automate/espresso/getting-started) or [XCUITest](https://www.browserstack.com/docs/app-automate/xcuitest/getting-started) endpoints when running on BrowserStack

**Comment by RuslikMer** [comment] 2023-10-02 07:40
so I tried with espresso endpoint and got same issue from browserstack "Could not start a session : Something went wrong. Please try to run the test again."

**Comment by bartekpacia** [comment] 2023-10-02 07:42
Then something might be configured wrong.

Please answer the questions I asked.

**Comment by RuslikMer** [comment] 2023-10-02 07:49
1)

> Hi @RuslikMer,
> 
> Please answer the following questions:
> 
> * Are you using a special runner (`BrowserstackPatrolJUnitRunner`) as explained in [the instruction](https://patrol.leancode.co/integrations/browserstack)?
> * What device and OS version are you running on?
> * Are you using the recommended [`bs_android`](https://github.com/leancodepl/mobile-tools/blob/master/bin/bs_android) script? I see you're not.
> * If you don't want to use that script, at least read its source code – you're using different endpoints than the required ones, and that's likely the problem.
> 
> > Also why did u provide in [instruction](https://patrol.leancode.co/integrations/browserstack) for patrol flutter link to espresso browserstack docs?
> 
> [Browserstack's support for Flutter](https://www.browserstack.com/docs/app-automate/flutter/getting-started) is dependent on the [`integration_test` plugin](https://github.com/flutter/flutter/tree/master/packages/integration_test), which [has many problems](https://leancode.co/blog/patrol-2-0-improved-flutter-ui-testing).
> 
> Among other things, Patrol is a revamped, rewritten version of the `integration_test` plugin. Patrol tests are visible to the native test framework as a normal test - that's why you need to use [Espresso](https://www.browserstack.com/docs/app-automate/espresso/getting-started) or [XCUITest](https://www.browserstack.com/docs/app-automate/xcuitest/getting-started) endpoints when running on BrowserStack

1) Yes I do 
<img width="1072" alt="Снимок экрана 2023-10-02 в 14 45 15" src="https://github.com/leancodepl/patrol/assets/30290012/ce32ff31-998f-4df3-9320-297ccc64fb95">
2)"devices": ["Samsung Galaxy S9 Plus-9.0"]
3) do manually because I waited for answer about bs_android problem in other topic

**Comment by RuslikMer** [comment] 2023-10-02 07:51
Now I did by bs_android 
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (8.4s)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  238M  100   243  100  238M     19  19.2M  0:00:12  0:00:12 --:--:--    62
Uploaded app, url: bs://3a2163b11a475ee409c7f24990439255cb61a6c5
Uploaded test, url: bs://9bb8c766c00e5d2a83c092ab74c21f3eaab7f6c1
{"message":"Success","build_id":"ea8c60bae8bda5f478af4b85b91f766e270a645d"}

and got same issue from BS

**Comment by bartekpacia** [comment] 2023-10-02 17:34
That's pretty weird, unfortunately I'm not able to help you without more info.

**Comment by RuslikMer** [comment] 2023-10-03 05:45
> That's pretty weird, unfortunately I'm not able to help you without more info.

I can provide any information u need

**Comment by RuslikMer** [comment] 2023-10-03 05:48
Or may u have some open source BS integrated test project  ?

**Comment by bartekpacia** [comment] 2023-10-03 08:25
Our example app works on BrowserStack. It's in `packages/patrol/example`. Use `bs_android` to run it (remember to change the runner in build.gradle).

**Comment by bartekpacia** [comment] 2023-10-26 18:36
Closing because no [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) was provided.

Feel free to open a new issue with all the required information provided.

I suggest you also contact BrowserStack since it's their cloud that does not share any logcat information if the test does not start.

**Closed by bartekpacia** 2023-10-26 18:36 UTC
