### ISSUE TITLE
apple review issue with patrol-urgent (  patrol: ^0.10.4)

### ISSUE THREAD

**Issue by neiljaywarner** [leancodepl/patrol#732] opened 2023-01-05 18:39 UTC
This happens even upon deployment via testflight.

ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/patrol.framework/patrol: terminate. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by bartekpacia** [comment] 2023-01-05 18:40
Hi @neiljaywarner, thanks for using Patrol and sorry for the problem.

This issue is a duplicate of #681 – the workaround is mentioned there.

**Comment by bartekpacia** [comment] 2023-01-05 18:41
Also, make sure you're using the latest version (0.10.6).

**Closed by bartekpacia** 2023-01-05 18:40 UTC

**Comment by neiljaywarner** [comment] 2023-01-05 20:08
Yeah great work! Patrol is awesome. I'm recommending it to people in our
organization.

....sent from my phone
