### ISSUE TITLE
Patrol doesn't work in WebView (Android/iOS)

### ISSUE THREAD

**Issue by henriquejunqbraga** [leancodepl/patrol#479] opened 2022-10-19 17:37 UTC
Hi people! 
I'm having trouble for patrol to work in webview, I can start the app in flutter, but when I get to the webview part, it can't interact with the fields,
can anybody help me?
Thx

**Comment by bartekpacia** [comment] 2022-10-19 19:56
Hi @henriquejunqbraga! Thanks for using Patrol and creating this issue 💙

This is a known issue – see #244. Unfortunately, the root of the problem is [a Flutter bug](https://github.com/flutter/flutter/issues/111110) and we can't do anything with this.

I'll add info to the feature parity table in the docs to say that WebView on Android doesn't work.

**Comment by bartekpacia** [comment] 2022-10-19 20:04
Info about missing WebView support for Android is added in #481.

**Comment by bartekpacia** [comment] 2022-10-19 20:09
@henriquejunqbraga The best you can do is to add a "👍" [to the Flutter issue I mentioned above](https://github.com/flutter/flutter/issues/111110) and ask your friends and coworkers, to do the same. This way that issue will gain visibility and there'll be a higher chance that Google fixes it.

**Comment by henriquejunqbraga** [comment] 2022-10-19 20:12
Thanks for the feedback, I will add a "👍" . I hope they help us with this.
And with IOS does patrol work with webview?

**Comment by bartekpacia** [comment] 2022-10-19 20:36
Thanks a lot!

> And with IOS does patrol work with webview?

Yes, it works like a charm (at least _on our achines!_ 😅) See below:

**Website A**
https://user-images.githubusercontent.com/40357511/196796370-e28c55c7-47b0-42a7-bca4-bc656677fc34.mp4

**Website B**


https://user-images.githubusercontent.com/40357511/196798753-f6b3ea3f-5f23-4bae-9b42-603d54fc18ca.mov

**Comment by henriquejunqbraga** [comment] 2022-10-19 20:42
Do i need to do something different? Or just run the same way?

**Comment by bartekpacia** [comment] 2022-10-19 20:46
It should work with no changes.

Let me know if you encounter any problems – we're gonna figure something out :)

**Comment by bartekpacia** [comment] 2022-10-19 21:26
I'm going to close this as a duplicate of #244.

**Comment by henriquejunqbraga** [comment] 2022-10-20 12:38
Hello @bartekpacia, it still didn't work here with IOS, it still doesn't interact... would you have any tips on how to capture the WebView elements?

**Comment by henriquejunqbraga** [comment] 2022-10-20 14:44
Sorry to bother you @bartekpacia and thanks for helping me. I made two videos.
One with await $(#login).tap(andSettle: false)
And another with await $(#login).tap();
One with await $(#login).tap(andSettle: false), cannot reach the WebView. The app closes
and the one with await $(#login).tap(); arrives at the WebView, but it gives
pumpAndSettle timed out


https://user-images.githubusercontent.com/110420689/196980867-50847cf3-26fc-407a-aa49-fb919a72abf6.mov

https://user-images.githubusercontent.com/110420689/196980895-95870338-c8a9-4dd0-9d18-792d8b48241c.mov

**Comment by bartekpacia** [comment] 2022-10-20 14:55
Okay, this makes sense.

Try this:

```dart
await $(#login).tap(andSettle: false);
await $.pump(Duration(seconds: 3)); // play with the duration
```

**Comment by henriquejunqbraga** [comment] 2022-10-20 17:13
@bartekpacia Hello man, I'm testing here, later I bring news. Thanks a lot for the help

**Comment by bartekpacia** [comment] 2022-10-20 18:13
@henriquejunqbraga I'm so happy you got it working :) Thanks for sharing the solution here so that time travelers from the future will be able to solve this faster.

Have fun testing apps with Patrol! 💙

**Closed** 2022-10-20 18:15 UTC
Labels: bug, automator: android

**Comment by henriquejunqbraga** [comment] 2022-10-20 19:29
I came back with one more doubt hahaha, right after logging in, I am directed to the home screen, where there is a key #lupa
but I can't get to this screen, do you have any tips?
thx

https://user-images.githubusercontent.com/110420689/197040335-7854378c-fbbd-4fc6-8df5-039e8a49115b.mov

**Comment by bartekpacia** [comment] 2022-10-20 19:37
Unfortunately, I can't help a lot without seeing the source code.

If you believe there's a bug, please create a new issue.

**Comment by henriquejunqbraga** [comment] 2022-10-20 19:57
I forgot to upload the video

Here! 
https://user-images.githubusercontent.com/110420689/197045416-0688eb52-cfc3-449b-bd33-f85283d9cccf.mp4

**Comment by bartekpacia** [comment] 2022-10-21 09:49
Looks like your app is throwing an exception, which causes the Flutter testing framework to abort execution of the test and fail it.

**Comment by henriquejunqbraga** [comment] 2022-10-21 17:46
You are right, my app is really having problems, i will solve them and get back to you
Thank you so much for your commitment and dedication!

**Comment by bartekpacia** [comment] 2022-10-21 18:13
You're welcome!

Thanks for using Patrol and helping us improve 💙
