### ISSUE TITLE
Display nice summary in the console after running tests

### ISSUE THREAD

**Issue by mateuszwojtczak** [leancodepl/patrol#1028] opened 2023-03-03 12:32 UTC

**Comment by bartekpacia** [comment] 2023-04-27 19:50
Here's the problem that this issue is about:

![Screenshot 2023-04-27 at 9 48 45 PM](https://user-images.githubusercontent.com/40357511/234975333-149738db-047b-4c66-b03d-475e93799fda.png)

Even though many tests were bundled, `patrol_cli` only knows that it executed `bundled_test.dart`.

We should either print a summary like this:

![Screenshot 2023-04-27 at 9 50 37 PM](https://user-images.githubusercontent.com/40357511/234975610-a1a005fb-5aec-416c-96d8-c5c8f8099055.png)


Or not print any results at all, and redirect users to the native report.

**Comment by bartekpacia** [comment] 2023-04-27 20:56
Another problem that should be resolved (let's say it's another AC to this issue).

The red text in top-left corner of the screen always displays `bundled_test.dart`. It should be fixed to display the exact bundled Dart test file being currently executed.

**Comment by jBorkowska** [comment] 2023-11-20 17:08
Closing as duplicate of #561

**Closed as completed by jBorkowska** 2023-11-20 17:08 UTC
