### ISSUE TITLE
Test is marked with a green "PASS" even when a test fails/doesnt complete - with native automation set up.

### ISSUE THREAD

**Issue by neiljaywarner** [leancodepl/patrol#947] opened 2023-02-16 16:45 UTC
I will try to give a MVCE in a bit or more details, but we have been having several tests failing - failing to complete, failing to achieve the desired result, etc, but no details, no flutter exception code or which part failed or anything and a PASS message.

eg
```
neil.warner@NA-081MD6TMBP blahblah % patrol test --target=integration_test/patrol/patrol_login_test.dart --flavor development --dart-define TESTING_ENVIRONMENT=dev3
No device specified, using the first one (594b4d3841563398)
• Building apk with entrypoint patrol_login_test.dart...
✓ Completed building apk with entrypoint patrol_login_test.dart (104.9s)
• Executing tests of apk with entrypoint patrol_login_test.dart on device 594b4d3841563398...
✓ Completed executing apk with entrypoint patrol_login_test.dart on device 594b4d3841563398 (138.6s)
 PASS  patrol_login_test.dart on 594b4d3841563398

```
Note
1) we *do* have native automation set up eg config: patrolConfig, nativeAutomation: true
2) we do have the pubspec.yaml patrol block 
3) output of verbose shows "Received 1 test target(s)"
4) but unfortunately output of verbose also shows 	: Starting 0 tests on SM-G960U1 - 10
5) however i get the purple test started, the red "patrol_login_test.dart" and our app opens and moves forward a bit.

**Comment by jeremiahlukus** [comment] 2023-02-17 14:48
might be related to 
https://github.com/leancodepl/patrol/issues/937

**Comment by bartekpacia** [comment] 2023-02-19 16:47
>  Starting 0 tests

This looks like an error in the configuration of native automation on Android. It probably passes because Gradle exits with code 0, and that's what Patrol looks at to determine if the call succeeded.

Please make sure you've done all [the required setup steps](https://patrol.leancode.co/native/setup#integrate-with-native-side). If the issue will still occur, I'll ask you to share a repo with a reproduction :)

**Comment by jeremiahlukus** [comment] 2023-02-19 20:13
This happened to me as well before I added flutter on error back.

**Comment by m-jayy** [comment] 2023-02-24 07:57
update your app-level build.gradle:

`android {
  // ...
  defaultConfig {
    //...
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}`

**Comment by bartekpacia** [comment] 2023-03-01 09:54
Please post an example project demonstrating this problem, otherwise I'm going to close it soon. @neiljaywarner

**Comment by bartekpacia** [comment] 2023-03-09 21:19
Closing because of lack of response. Feel free to comment and I'll be happy to continue the discussion :)

**Closed by bartekpacia** 2023-03-09 21:19 UTC

**Comment by oberoivarun** [comment] 2023-08-13 15:08
> > Starting 0 tests
> 
> This looks like an error in the configuration of native automation on Android. It probably passes because Gradle exits with code 0, and that's what Patrol looks at to determine if the call succeeded.
> 
> Please make sure you've done all [the required setup steps](https://patrol.leancode.co/native/setup#integrate-with-native-side). If the issue will still occur, I'll ask you to share a repo with a reproduction :)

Hey, Just a suggestion, if you have a working example of the starting configuration as in the docs, please post a link so we can refer and match.

I have a whole bunch of red lines in my MainActivity.java

![image](https://github.com/leancodepl/patrol/assets/13959202/bcc4abb3-27d8-4461-abfa-d1f80af909be)

And I don't even know what issue to post since `patrol test` return a success message and there is nothing happening in the emulator.

```
PS C:\Users\obero\code\odac\ui\apps\poc> patrol test --target integration_test\example_test.dart         
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

No device specified, using the first one (emulator-5554)
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (16.7s)
• Executing tests of apk with entrypoint test_bundle.dart on emulator-5554...
✓ Completed executing apk with entrypoint test_bundle.dart on emulator-5554
```
