### ISSUE TITLE
drag feature

### ISSUE THREAD

**Issue by AcarFurkan** [leancodepl/patrol#2100] opened 2024-02-09 14:53 UTC
### Use case

 await tester.drag($('x'), const Offset(0, 1000)); 
await tester.pumpAndSettle(); 

### Proposal

cam l do this with patrol. l couldn't drag feature

**Comment by jBorkowska** [comment] 2024-02-09 14:59
Hi @AcarFurkan, you can do this now, but using original Flutter `WidgetTester`. Eg.:
```
await $.tester.drag($('x'), const Offset(0, 1000));
await $.pumpAndSettle();
```

This way you can access all Flutter's `integration_test` package features. In general, we plan to add more swiping/dragging methods to Patrol directly.

**Comment by jBorkowska** [comment] 2024-02-09 15:00
Closing as duplicate of https://github.com/leancodepl/patrol/issues/1399

**Closed by jBorkowska** 2024-02-09 15:00 UTC
