### ISSUE TITLE
All tests except first one always fails when running patrol tests on Saucelab android emulator devices

### ISSUE THREAD

**Issue by rohitbhoite** [leancodepl/patrol#2380] opened 2024-10-23 16:34 UTC
### Steps to reproduce

I am trying to run flutter patrol based integration tests on saucelab Android emulators. The issue is all tests starting with second test always fails with below error message.  First test executes successfully with success response but next tests does not start and all tests gives same error message.
java.lang.RuntimeException: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 500, Internal Server Error
	at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:155)
	at com.corelogic.clvs.homeinspector.MainActivityTest.runDartTest(MainActivityTest.java:32)
	... 39 trimmed
Caused by: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 500, Internal Server Error
	at pl.leancode.patrol.contracts.PatrolAppServiceClient.performRequest(PatrolAppServiceClient.kt:47)
	at pl.leancode.patrol.contracts.PatrolAppServiceClient.runDartTest(PatrolAppServiceClient.kt:23)
	at pl.leancode.patrol.PatrolAppServiceClient.runDartTest(PatrolAppServiceClient.kt:53)
	at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:148)

### Actual results

java.lang.RuntimeException: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 500, Internal Server Error
	at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:155)
	at com.corelogic.clvs.homeinspector.MainActivityTest.runDartTest(MainActivityTest.java:32)
	... 39 trimmed
Caused by: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 500, Internal Server Error
	at pl.leancode.patrol.contracts.PatrolAppServiceClient.performRequest(PatrolAppServiceClient.kt:47)
	at pl.leancode.patrol.contracts.PatrolAppServiceClient.runDartTest(PatrolAppServiceClient.kt:23)
	at pl.leancode.patrol.PatrolAppServiceClient.runDartTest(PatrolAppServiceClient.kt:53)
	at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:148)

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

^3.11.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 3.2.0
Flutter command: flutter 
  Flutter 3.24.3 • channel stable
Android: 
• Program adb found in /Users/rohit_bhoite/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/rohit_bhoite/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.1)
[✓] VS Code (version 1.94.2)
[✓] Connected device (4 available)
[✓] Network resources

```

</details>

**Comment by rohitbhoite** [comment] 2024-10-23 17:02
Also tested it on patrol 3.11.2 but got same error


<img width="724" alt="Screenshot 2024-10-23 at 10 29 56 PM" src="https://github.com/user-attachments/assets/134866a1-8bb9-45af-b465-6f581c28d677">

**Comment by rohitbhoite** [comment] 2024-10-23 17:04
Also tested it on patrol version 3.11.2 but got same error.


<img width="724" alt="Screenshot 2024-10-23 at 10 29 56 PM" src="https://github.com/user-attachments/assets/afcbe0d3-d822-47de-9e45-2c321dbffa3b">

**Comment by jigar-f** [comment] 2024-10-23 17:56
I'm experiencing the same issue. When I try to run multiple tests, I get an error, but running them individually works fine.

**Comment by piotruela** [comment] 2024-10-24 09:38
Please post here `device.log` file with **VERBOSE** option selected. You can find them in 'Test Details' of a test that failed

**Comment by rohitbhoite** [comment] 2024-10-24 13:24
[logcat.log](https://github.com/user-attachments/files/17507462/logcat.log)

**Comment by rohitbhoite** [comment] 2024-10-24 13:25
Have shared the log file. What could be the reason for this?

**Comment by piotruela** [comment] 2024-10-24 14:16
Thanks for sharing the logs. The tests are failing due to an exception that is thrown during the execution.
```
10-23 16:55:39.779  4959  4995 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Type GeocodingManager is already registered inside GetIt. 
10-23 16:55:39.779  4959  4995 E flutter : #0      throwIfNot (package:get_it/get_it_impl.dart:14:19)
10-23 16:55:39.779  4959  4995 E flutter : #1      _GetItImplementation._register (package:get_it/get_it_impl.dart:1097:11)
10-23 16:55:39.779  4959  4995 E flutter : #2      _GetItImplementation.registerSingleton (package:get_it/get_it_impl.dart:762:5)
10-23 16:55:39.779  4959  4995 E flutter : #3      SharedDependencyConfigurator.configureDependencies (package:shared/shared_dependency_cofigurator.dart:17:11)
10-23 16:55:39.779  4959  4995 E flutter : #4      AppDependencies.configureDependencies (package:home_inspector_ui/dependencies.dart:22:26)
10-23 16:55:39.779  4959  4995 E flutter : #5      setupDependencies (file:///Users/rohit_bhoite/project_repo/integration_test/settings_test.dart:27:8)
10-23 16:55:39.779  4959  4995 E flutter : #6      main (file:///Users/rohit_bhoite/project_repo/integration_test/settings_test.dart:11:3)
10-23 16:55:39.779  4959  4995 E flutter : #7      Declarer.group.<anonymous closure> (package:test_api/src/backend/declarer.dart:267:37)
10-23 16:55:39.779  4959  4995 E flutter : #8      _rootRun (dart:async/zone.dart:1399:13)
10-23 16:55:39.779  4959  4995 E flutter : #9      _CustomZone.run (dart:async/zone.dart:1301:19)
10-23 16:55:39.779  4959  4995 E flutter : #10     _runZoned (dart:async/zone.dart:1826:10)
10-23 16:55:39.779  4959  4995 E flutter : #11     runZoned (dart:async/zone.dart:1763:10)
10-23 16:55:39.779  4959  4995 E flutter : #12     Declarer.declare (package:test_api/src/backend/declarer.dart:169:7)
10-23 16:55:39.779  4959  4995 E flutter : #13     Declarer.group (package:test_api/src/backend/declarer.dart:264:14)
10-23 16:55:39.779  4959  4995 E flutter : #14     group (package:flutter_test/src/test_compat.dart:195:13)
10-23 16:55:39.779  4959  4995 E flutter : #15     main (file:///Users/rohit_bhoite/project_repo/integration_test/test_bundle.dart:75:3)
10-23 16:55:39.779  4959  4995 E flutter : <asynchronous suspension>
```
Solve those issues in the project and try running them again.
That being said, this is not a bug in Patrol repository, nor in SauceLabs so closing this issue for now.
If you have any more questions please raise those on [Patrol Discord Server](https://discord.gg/ukBK5t4EZg).

**Closed by piotruela** 2024-10-24 14:16 UTC

**Comment by rohitbhoite** [comment] 2024-10-24 14:25
But How does it work if I run these tests locally using `patrol test android ` command.

**Comment by piotruela** [comment] 2024-10-25 05:44
Hard to tell, but I would try settings [`clearPackageData`](https://docs.saucelabs.com/mobile-apps/automated-testing/espresso-xcuitest/espresso/#clearpackagedata) and [`useTestOrchestrator`](https://docs.saucelabs.com/mobile-apps/automated-testing/espresso-xcuitest/espresso/#usetestorchestrator) in the config file to `true`.
