### ISSUE TITLE
Unable to run tests on physical devices

### ISSUE THREAD

**Issue by Skisperd** [leancodepl/patrol#1949] opened 2023-11-23 09:42 UTC
### Steps to reproduce

patrol test --target integration_test\resources\tests/login\login_test.dart --flavor dev --release

### Actual results

`Building apk with entrypoint test_bundle.dart...
        integration_test/test_bundle.dart:50:50: Error: Too many positional arguments: 0 allowed, but 1 found.
        Try removing the extra positional arguments.
          final binding = PatrolBinding.ensureInitialized(NativeAutomatorConfig());
                                                         ^
        /C:/Users/tfdia/AppData/Local/Pub/Cache/hosted/pub.dev/patrol-2.3.2/lib/src/binding.dart:104:11: Context: Found this candidate, but the arguments don't match.
          factory PatrolBinding.ensureInitialized() {
                  ^^^^^^^^^^^^^^^^^
        Target kernel_snapshot failed: Exception

        FAILURE: Build failed with an exception.`
![Captura de tela 2023-11-23 053917](https://github.com/leancodepl/patrol/assets/30876280/14d32a9a-e275-48bb-be91-6845ad5fc674)

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol_cli v2.3.0

Patrol 2.3.2

### Patrol Doctor output

![Captura de tela 2023-11-23 054106](https://github.com/leancodepl/patrol/assets/30876280/c9ac349d-ab9e-4cce-a23a-c99051b3ff10)

### Flutter Doctor output

![Captura de tela 2023-11-23 054151](https://github.com/leancodepl/patrol/assets/30876280/7f4e54e8-2d39-4d25-b9f9-9d1300805e0b)

**Comment by jBorkowska** [comment] 2023-11-23 13:22
Hi @Skisperd! I see that you use patrol 2.3.2, so you should use older CLI - version 2.2.2 instead of 2.3.0, bc the newer one requires at least patrol v3.0.

Closing as it is not a bug, if you find a bug or have a feature request, please open new issue. If you have another questions, join our Discord, we'll try to help you there. Link to Discord: https://discord.gg/K5hq2Stw

**Closed by jBorkowska** 2023-11-23 13:22 UTC

**Comment by Origogi** [comment] 2023-11-23 13:32
@jBorkowska 
I want to join discord but invalid link

**Comment by jBorkowska** [comment] 2023-11-23 13:46
That's weird. Anyway, here's new link: https://discord.gg/G4hWHbqY
