### ISSUE TITLE
Upgrading to patrol 0.10.x

### ISSUE THREAD

**Issue by ds3031** [leancodepl/patrol#705] opened 2022-12-22 11:43 UTC
Hi

Upgrade to patrol 0.10.x gives me this output error when I run test with
`patrol drive --flavor dev --target integration_test/simple_test.dart --device=emulator-5554`

<details>
<summary>Logs</summary>

```
This is the output:
`        FAILURE: Build failed with an exception.
        * What went wrong:
        Execution failed for task ':app:checkDevDebugDuplicateClasses'.
        > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
        > Duplicate class com.google.protobuf.AbstractMessageLite found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.AbstractMessageLite$Builder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.AbstractMessageLite$Builder$LimitedInputStream found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.AbstractMessageLite$InternalOneOfEnum found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.AbstractParser found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.AbstractProtobufList found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.AllocatedBuffer found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.AllocatedBuffer$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.AllocatedBuffer$2 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Android found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Any found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Any$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Any$Builder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.AnyOrBuilder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.AnyProto found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Api found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Api$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Api$Builder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ApiOrBuilder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ApiProto found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ArrayDecoders found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ArrayDecoders$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ArrayDecoders$Registers found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BinaryReader found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BinaryReader$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BinaryReader$SafeHeapReader found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BinaryWriter found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BinaryWriter$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BinaryWriter$SafeDirectWriter found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BinaryWriter$SafeHeapWriter found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.BinaryWriter$UnsafeDirectWriter found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BinaryWriter$UnsafeHeapWriter found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BoolValue found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BoolValue$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.BoolValue$Builder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.BoolValueOrBuilder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.BooleanArrayList found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.BufferAllocator found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.BufferAllocator$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.ByteBufferWriter found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.ByteOutput found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.ByteString found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.ByteString$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ByteString$2 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ByteString$AbstractByteIterator found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ByteString$ArraysByteArrayCopier found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ByteString$BoundedByteString found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ByteString$ByteArrayCopier found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ByteString$ByteIterator found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ByteString$CodedBuilder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ByteString$LeafByteString found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ByteString$LiteralByteString found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ByteString$Output found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ByteString$SystemByteArrayCopier found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BytesValue found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BytesValue$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BytesValue$Builder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.BytesValueOrBuilder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedInputStream found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedInputStream$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedInputStream$ArrayDecoder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedInputStream$IterableDirectByteBufferDecoder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedInputStream$StreamDecoder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.CodedInputStream$StreamDecoder$RefillCallback found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedInputStream$StreamDecoder$SkippedDataSink found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedInputStream$UnsafeDirectNioDecoder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedInputStreamReader found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedInputStreamReader$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedOutputStream found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedOutputStream$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedOutputStream$AbstractBufferedEncoder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedOutputStream$ArrayEncoder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedOutputStream$ByteOutputEncoder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedOutputStream$HeapNioEncoder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedOutputStream$OutOfSpaceException found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedOutputStream$OutputStreamEncoder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedOutputStream$SafeDirectNioEncoder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedOutputStream$UnsafeDirectNioEncoder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedOutputStreamWriter found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.CodedOutputStreamWriter$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.DoubleArrayList found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.DoubleValue found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.DoubleValue$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.DoubleValue$Builder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.DoubleValueOrBuilder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Duration found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Duration$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Duration$Builder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
        Duplicate class com.google.protobuf.DurationOrBuilder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.DurationProto found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Empty found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Empty$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Empty$Builder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.EmptyOrBuilder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.EmptyProto found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Enum found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Enum$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.Enum$Builder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.EnumOrBuilder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.EnumValue found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.EnumValue$1 found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.EnumValue$Builder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.EnumValueOrBuilder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ExperimentalApi found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ExtensionLite found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ExtensionRegistryFactory found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ExtensionRegistryLite found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     Duplicate class com.google.protobuf.ExtensionRegistryLite$ExtensionClassHolder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.21.7 (com.google.protobuf:protobuf-javalite:3.21.7)
     ...

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`
```
</details>

Is this the same or similar to https://github.com/leancodepl/patrol/issues/680 ?
Works without this error with v0.9.1

Thanks

**Comment by bartekpacia** [comment] 2022-12-22 12:10
Hi,

This indeed sounds very similar to #680. Please post more info: version of patrol and patrol_cli you're using, your app's `pubspec.yaml` file, whether you're using gRPC or protobufs or Firebase in your app etc. :)

**Comment by ds3031** [comment] 2022-12-22 12:43
patrol 0.9.1
patrol_cli 0.8.1
we use Firebase plugins (firebase_core: ^1.19.1, firebase_dynamic_links: 2.0.5, firebase_analytics: ^9.2.0, firebase_crashlytics: ^2.5.0 and firebase_core_platform_interface: 4.5.1)

I have to contact our dev about pubspec.yaml :)

**Comment by bartekpacia** [comment] 2022-12-22 12:49
Well, this is strange. I think this error was introduced in `v0.10.0`, but you're encountering it in 0.9.1.

Please update to the newest version and let me know if this problem occurs.

**Comment by ds3031** [comment] 2022-12-22 12:58
We misunderstood each other. This error was in every patrol 0.10.x version. I reverted back to v0.9.1 so I can write/run my tests

**Comment by bartekpacia** [comment] 2022-12-22 13:01
Ah, sure :)

> This error was in every patrol 0.10.x version

This is what's strange to me, because other people had a very similar problem in #680 and it was fixed in `patrol v0.10.4`. So your case is something different and I've no idea what could be causing this 🤔

**Comment by ds3031** [comment] 2022-12-22 13:10
Only diff I made is that I put patrol in **dev_dependencies** not **dependencies** Maybe this is the problem?

**Comment by bartekpacia** [comment] 2022-12-22 21:30
Patrol should be in `dev_dependencies` – what you did is correct.

🤔

**Comment by ds3031** [comment] 2022-12-23 08:15
I see I didn't paste maybe most important part of output. Maybe it can help you more?

`2: Task failed with an exception.
* What went wrong:
Execution failed for task :app:mergeDevDebugJavaResource.
A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   2 files found with path google/protobuf/field_mask.proto.
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information
`

**Comment by bartekpacia** [comment] 2023-01-12 14:30
Closing because of lack of response. Feel free to create a new issue with [a minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) and I'll be happy to continue the discussion :)

**Closed by bartekpacia** 2023-01-12 14:30 UTC
Labels: bug, platform: android

**Comment by ds3031** [comment] 2023-01-20 06:15
lol
