### ISSUE TITLE
Using slash "/" in tests names yields a test runner error when running all tests

### ISSUE THREAD

**Issue by adrian-moisa** [leancodepl/patrol#2089] opened 2024-02-04 13:16 UTC
### Steps to reproduce

Write any test you desire.
Add a slash in the test name
Run all tests

<img width="874" alt="image" src="https://github.com/leancodepl/patrol/assets/11160141/f3b16423-e26b-44a0-a18a-6d4333897971">

### Actual results

A error shows up in the terminal. The tests that were supposed to run after the faulty test no longer run.
Removing the slash eliminates this issue and tests return to running normally.

### Logs

<details>
<summary>Logs</summary>

```
patrol test
No device specified, using the first one (emulator-5554)
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (14.5s)
• Executing tests of apk with entrypoint test_bundle.dart on emulator-5554...
        See the report at: file:///Users/ ... /build/app/reports/androidTests/connected/index.html
✗ Failed to execute tests of apk with entrypoint test_bundle.dart on emulator-5554 (Gradle test execution failed with code 1) (23.9s)
Exception: Gradle test execution failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.

// === ALSO THE VERBOSE STACK TRACE ===

        BUILD FAILED in 26s
✗ Failed to execute tests of apk with entrypoint test_bundle.dart on emulator-5554 (Gradle test execution failed with code 1) (27.2s)
Exception: Gradle test execution failed with code 1
#0      AndroidTestBackend.execute.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:140:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.execute (package:patrol_cli/src/android/android_test_backend.dart:106:5)
<asynchronous suspension>
#3      TestCommand._execute (package:patrol_cli/src/commands/test.dart:309:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:201:23)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:341:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:285:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#9      main (file:///Users/adrianmoisa/.pub-cache/hosted/pub.dev/patrol_cli-2.6.2/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.


```

</details>

### Patrol version

patrol: 3.5.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.6.2
Android: 
• Program adb found in /opt/homebrew/bin/adb
• Env var $ANDROID_HOME set to ~/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.2 23C64 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.2)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by piotruela** [comment] 2024-02-05 12:25
Hi @adrian-moisa. Thanks for opening the issue. I was able to reproduce it on Android. We should either find a way to allow `/` in the test name (for example, by replacing it with another character during execution) or warn users that they cannot use `/` there.

**Comment by bartekpacia** [comment] 2024-02-06 11:10
likely a duplicate of #1839

**Comment by piotruela** [comment] 2024-02-06 13:25
Thanks @bartekpacia for keeping an eye. That's definitely a duplicate of #1839 therefore closing it.

**Closed by piotruela** 2024-02-06 13:25 UTC
Labels: bug, platform: android, P2
