### ISSUE TITLE
Example app patrol develop Null pointer error with example project and patrol develop --target integration_test/android_app_test.dart    

### ISSUE THREAD

**Issue by neiljaywarner** [leancodepl/patrol#1959] opened 2023-11-28 05:05 UTC
### Steps to reproduce

1. Plug in device and `git clone https://github.com/leancodepl/patrol.git`
2. make sure patrol cli is installed  (patrol_cli v2.3.1+1)
3. run patrol develop on existing test

### Actual results

1) Example app NPEs within geoocator, notifications, etc
2) also it says
"If the logs still aren't useful, then it's a bug - please report it."

### Logs

<details>
<summary>Logs</summary>

```
 patrol develop --target integration_test/android_app_test.dart --verbose
Verbose mode enabled. More logs will be printed.
Received test target: /Users/Neil.Warner/dev/patrol/packages/patrol/example/integration_test/android_app_test.dart
Generated entrypoint /Users/Neil.Warner/dev/patrol/packages/patrol/example/integration_test/test_bundle.dart for development
$ flutter --no-version-check devices --machine
No device specified, using the first one (24061FDF6003TX)
Received device: 24061FDF6003TX
Received 8 --dart-define(s) (0 custom, 8 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=pl.leancode.patrol.example
Received internal --dart-define: PATROL_APP_BUNDLE_ID=pl.leancode.patrol.Example
Received internal --dart-define: PATROL_ANDROID_APP_NAME=Patrol example
Received internal --dart-define: PATROL_IOS_APP_NAME=Patrol example
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
Received internal --dart-define: PATROL_HOT_RESTART=true
• Building apk with entrypoint test_bundle.dart...
$ ./gradlew :app:assembleDebug -Ptarget=/Users/Neil.Warner/dev/patrol/packages/patrol/example/integration_test/test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9cGwubGVhbmNvZGUucGF0cm9sLmV4YW1wbGU=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9cGwubGVhbmNvZGUucGF0cm9sLkV4YW1wbGU=,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9UGF0cm9sIGV4YW1wbGU=,UEFUUk9MX0lPU19BUFBfTkFNRT1QYXRyb2wgZXhhbXBsZQ==,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl,UEFUUk9MX0hPVF9SRVNUQVJUPXRydWU=
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
        : > Task :app:compileFlutterBuildDebug
        : > Task :app:packLibsflutterBuildDebug UP-TO-DATE
        : > Task :flutter_local_notifications:preBuild UP-TO-DATE
        : > Task :flutter_local_notifications:preDebugBuild UP-TO-DATE
        : > Task :flutter_local_notifications:compileDebugAidl NO-SOURCE
        : > Task :flutter_timezone:preBuild UP-TO-DATE
        : > Task :flutter_timezone:preDebugBuild UP-TO-DATE
        : > Task :flutter_timezone:compileDebugAidl NO-SOURCE
        : > Task :geolocator_android:preBuild UP-TO-DATE
        : > Task :geolocator_android:preDebugBuild UP-TO-DATE
        : > Task :geolocator_android:compileDebugAidl NO-SOURCE
        : > Task :patrol:preBuild UP-TO-DATE
        : > Task :patrol:preDebugBuild UP-TO-DATE
        : > Task :patrol:compileDebugAidl NO-SOURCE
        : > Task :permission_handler_android:preBuild UP-TO-DATE
        : > Task :permission_handler_android:preDebugBuild UP-TO-DATE
        : > Task :permission_handler_android:compileDebugAidl NO-SOURCE
        : > Task :webview_flutter_android:preBuild UP-TO-DATE
        : > Task :webview_flutter_android:preDebugBuild UP-TO-DATE
        : > Task :webview_flutter_android:compileDebugAidl NO-SOURCE
        : > Task :app:compileDebugAidl NO-SOURCE
        : > Task :flutter_local_notifications:packageDebugRenderscript NO-SOURCE
        : > Task :flutter_timezone:packageDebugRenderscript NO-SOURCE
        : > Task :geolocator_android:packageDebugRenderscript NO-SOURCE
        : > Task :patrol:packageDebugRenderscript NO-SOURCE
        : > Task :permission_handler_android:packageDebugRenderscript NO-SOURCE
        : > Task :webview_flutter_android:packageDebugRenderscript NO-SOURCE
        : > Task :app:compileDebugRenderscript NO-SOURCE
        : > Task :app:generateDebugBuildConfig UP-TO-DATE
        : > Task :flutter_local_notifications:writeDebugAarMetadata UP-TO-DATE
        : > Task :flutter_timezone:writeDebugAarMetadata UP-TO-DATE
        : > Task :geolocator_android:writeDebugAarMetadata UP-TO-DATE
        : > Task :patrol:writeDebugAarMetadata UP-TO-DATE
        : > Task :permission_handler_android:writeDebugAarMetadata UP-TO-DATE
        : > Task :webview_flutter_android:writeDebugAarMetadata UP-TO-DATE
        : > Task :app:checkDebugAarMetadata UP-TO-DATE
        : > Task :app:cleanMergeDebugAssets
        : > Task :app:mergeDebugShaders UP-TO-DATE
        : > Task :app:compileDebugShaders NO-SOURCE
        : > Task :app:generateDebugAssets UP-TO-DATE
        : > Task :flutter_local_notifications:mergeDebugShaders UP-TO-DATE
        : > Task :flutter_local_notifications:compileDebugShaders NO-SOURCE
        : > Task :flutter_local_notifications:generateDebugAssets UP-TO-DATE
        : > Task :flutter_local_notifications:packageDebugAssets UP-TO-DATE
        : > Task :flutter_timezone:mergeDebugShaders UP-TO-DATE
        : > Task :flutter_timezone:compileDebugShaders NO-SOURCE
        : > Task :flutter_timezone:generateDebugAssets UP-TO-DATE
        : > Task :flutter_timezone:packageDebugAssets UP-TO-DATE
        : > Task :geolocator_android:mergeDebugShaders UP-TO-DATE
        : > Task :geolocator_android:compileDebugShaders NO-SOURCE
        : > Task :geolocator_android:generateDebugAssets UP-TO-DATE
        : > Task :geolocator_android:packageDebugAssets UP-TO-DATE
        : > Task :patrol:mergeDebugShaders UP-TO-DATE
        : > Task :patrol:compileDebugShaders NO-SOURCE
        : > Task :patrol:generateDebugAssets UP-TO-DATE
        : > Task :patrol:packageDebugAssets UP-TO-DATE
        : > Task :permission_handler_android:mergeDebugShaders UP-TO-DATE
        : > Task :permission_handler_android:compileDebugShaders NO-SOURCE
        : > Task :permission_handler_android:generateDebugAssets UP-TO-DATE
        : > Task :permission_handler_android:packageDebugAssets UP-TO-DATE
        : > Task :webview_flutter_android:mergeDebugShaders UP-TO-DATE
        : > Task :webview_flutter_android:compileDebugShaders NO-SOURCE
        : > Task :webview_flutter_android:generateDebugAssets UP-TO-DATE
        : > Task :webview_flutter_android:packageDebugAssets UP-TO-DATE
        : > Task :app:mergeDebugAssets
        : > Task :app:copyFlutterAssetsDebug
        : > Task :app:generateDebugResValues UP-TO-DATE
        : > Task :flutter_local_notifications:compileDebugRenderscript NO-SOURCE
        : > Task :flutter_local_notifications:generateDebugResValues UP-TO-DATE
        : > Task :flutter_local_notifications:generateDebugResources UP-TO-DATE
        : > Task :flutter_local_notifications:packageDebugResources UP-TO-DATE
        : > Task :flutter_timezone:compileDebugRenderscript NO-SOURCE
        : > Task :flutter_timezone:generateDebugResValues UP-TO-DATE
        : > Task :flutter_timezone:generateDebugResources UP-TO-DATE
        : > Task :flutter_timezone:packageDebugResources UP-TO-DATE
        : > Task :geolocator_android:compileDebugRenderscript NO-SOURCE
        : > Task :geolocator_android:generateDebugResValues UP-TO-DATE
        : > Task :geolocator_android:generateDebugResources UP-TO-DATE
        : > Task :geolocator_android:packageDebugResources UP-TO-DATE
        : > Task :patrol:compileDebugRenderscript NO-SOURCE
        : > Task :patrol:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResources UP-TO-DATE
        : > Task :patrol:packageDebugResources UP-TO-DATE
        : > Task :permission_handler_android:compileDebugRenderscript NO-SOURCE
        : > Task :permission_handler_android:generateDebugResValues UP-TO-DATE
        : > Task :permission_handler_android:generateDebugResources UP-TO-DATE
        : > Task :permission_handler_android:packageDebugResources UP-TO-DATE
        : > Task :webview_flutter_android:compileDebugRenderscript NO-SOURCE
        : > Task :webview_flutter_android:generateDebugResValues UP-TO-DATE
        : > Task :webview_flutter_android:generateDebugResources UP-TO-DATE
        : > Task :webview_flutter_android:packageDebugResources UP-TO-DATE
        : > Task :app:mapDebugSourceSetPaths UP-TO-DATE
        : > Task :app:generateDebugResources UP-TO-DATE
        : > Task :app:mergeDebugResources UP-TO-DATE
        : > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
        : > Task :app:extractDeepLinksDebug UP-TO-DATE
        : > Task :flutter_local_notifications:extractDeepLinksDebug UP-TO-DATE
        : > Task :flutter_local_notifications:processDebugManifest UP-TO-DATE
        : > Task :flutter_timezone:extractDeepLinksDebug UP-TO-DATE
        : > Task :flutter_timezone:processDebugManifest UP-TO-DATE
        : > Task :geolocator_android:extractDeepLinksDebug UP-TO-DATE
        : > Task :geolocator_android:processDebugManifest UP-TO-DATE
        : > Task :patrol:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:processDebugManifest UP-TO-DATE
        : > Task :permission_handler_android:extractDeepLinksDebug UP-TO-DATE
        : > Task :permission_handler_android:processDebugManifest UP-TO-DATE
        : > Task :webview_flutter_android:extractDeepLinksDebug UP-TO-DATE
        : > Task :webview_flutter_android:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugMainManifest UP-TO-DATE
        : > Task :app:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugManifestForPackage UP-TO-DATE
        : > Task :flutter_local_notifications:compileDebugLibraryResources UP-TO-DATE
        : > Task :flutter_local_notifications:parseDebugLocalResources UP-TO-DATE
        : > Task :flutter_local_notifications:generateDebugRFile UP-TO-DATE
        : > Task :flutter_timezone:compileDebugLibraryResources UP-TO-DATE
        : > Task :flutter_timezone:parseDebugLocalResources UP-TO-DATE
        : > Task :flutter_timezone:generateDebugRFile UP-TO-DATE
        : > Task :geolocator_android:compileDebugLibraryResources UP-TO-DATE
        : > Task :geolocator_android:parseDebugLocalResources UP-TO-DATE
        : > Task :geolocator_android:generateDebugRFile UP-TO-DATE
        : > Task :patrol:compileDebugLibraryResources UP-TO-DATE
        : > Task :patrol:parseDebugLocalResources UP-TO-DATE
        : > Task :patrol:generateDebugRFile UP-TO-DATE
        : > Task :permission_handler_android:compileDebugLibraryResources UP-TO-DATE
        : > Task :permission_handler_android:parseDebugLocalResources UP-TO-DATE
        : > Task :permission_handler_android:generateDebugRFile UP-TO-DATE
        : > Task :webview_flutter_android:compileDebugLibraryResources UP-TO-DATE
        : > Task :webview_flutter_android:parseDebugLocalResources UP-TO-DATE
        : > Task :webview_flutter_android:generateDebugRFile UP-TO-DATE
        : > Task :app:processDebugResources UP-TO-DATE
        : > Task :flutter_local_notifications:generateDebugBuildConfig UP-TO-DATE
        : > Task :flutter_local_notifications:javaPreCompileDebug UP-TO-DATE
        : > Task :flutter_local_notifications:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :flutter_local_notifications:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :flutter_timezone:generateDebugBuildConfig UP-TO-DATE
        : > Task :flutter_timezone:compileDebugKotlin UP-TO-DATE
        : > Task :flutter_timezone:javaPreCompileDebug UP-TO-DATE
        : > Task :flutter_timezone:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :flutter_timezone:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :geolocator_android:generateDebugBuildConfig UP-TO-DATE
        : > Task :geolocator_android:javaPreCompileDebug UP-TO-DATE
        : > Task :geolocator_android:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :geolocator_android:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :patrol:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:compileDebugKotlin UP-TO-DATE
        : > Task :patrol:javaPreCompileDebug UP-TO-DATE
        : > Task :patrol:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :patrol:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :permission_handler_android:generateDebugBuildConfig UP-TO-DATE
        : > Task :permission_handler_android:javaPreCompileDebug UP-TO-DATE
        : > Task :permission_handler_android:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :permission_handler_android:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :webview_flutter_android:generateDebugBuildConfig UP-TO-DATE
        : > Task :webview_flutter_android:javaPreCompileDebug UP-TO-DATE
        : > Task :webview_flutter_android:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :webview_flutter_android:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :app:compileDebugKotlin UP-TO-DATE
        : > Task :app:javaPreCompileDebug UP-TO-DATE
        : > Task :app:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :app:compressDebugAssets UP-TO-DATE
        : > Task :app:processDebugJavaRes NO-SOURCE
        : > Task :flutter_local_notifications:processDebugJavaRes NO-SOURCE
        : > Task :flutter_local_notifications:bundleLibResDebug NO-SOURCE
        : > Task :flutter_timezone:processDebugJavaRes NO-SOURCE
        : > Task :flutter_timezone:bundleLibResDebug UP-TO-DATE
        : > Task :geolocator_android:processDebugJavaRes NO-SOURCE
        : > Task :geolocator_android:bundleLibResDebug NO-SOURCE
        : > Task :patrol:processDebugJavaRes NO-SOURCE
        : > Task :patrol:bundleLibResDebug UP-TO-DATE
        : > Task :permission_handler_android:processDebugJavaRes NO-SOURCE
        : > Task :permission_handler_android:bundleLibResDebug NO-SOURCE
        : > Task :webview_flutter_android:processDebugJavaRes NO-SOURCE
        : > Task :webview_flutter_android:bundleLibResDebug NO-SOURCE
        : > Task :app:mergeDebugJavaResource UP-TO-DATE
        : > Task :app:checkDebugDuplicateClasses UP-TO-DATE
        : > Task :app:desugarDebugFileDependencies UP-TO-DATE
        : > Task :app:mergeExtDexDebug UP-TO-DATE
        : > Task :patrol:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :flutter_timezone:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :permission_handler_android:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :geolocator_android:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :flutter_local_notifications:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :webview_flutter_android:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :app:dexBuilderDebug UP-TO-DATE
        : > Task :app:mergeProjectDexDebug UP-TO-DATE
        : > Task :app:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :flutter_local_notifications:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :flutter_local_notifications:mergeDebugNativeLibs NO-SOURCE
        : > Task :flutter_local_notifications:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :flutter_timezone:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :flutter_timezone:mergeDebugNativeLibs NO-SOURCE
        : > Task :flutter_timezone:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :geolocator_android:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :geolocator_android:mergeDebugNativeLibs NO-SOURCE
        : > Task :geolocator_android:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :patrol:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugNativeLibs NO-SOURCE
        : > Task :patrol:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :permission_handler_android:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :permission_handler_android:mergeDebugNativeLibs NO-SOURCE
        : > Task :permission_handler_android:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :webview_flutter_android:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :webview_flutter_android:mergeDebugNativeLibs NO-SOURCE
        : > Task :webview_flutter_android:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :app:mergeDebugNativeLibs UP-TO-DATE
        : > Task :app:stripDebugDebugSymbols UP-TO-DATE
        : > Task :app:validateSigningDebug UP-TO-DATE
        : > Task :app:writeDebugAppMetadata UP-TO-DATE
        : > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
        : 
        : > Transform classes.jar (project :geolocator_android) with DexingWithClasspathTransform
        : 
        : > Transform classes.jar (project :flutter_local_notifications) with DexingWithClasspathTransform
        : 
        : > Transform classes.jar (project :webview_flutter_android) with DexingWithClasspathTransform
        : 
        : > Task :app:mergeLibDexDebug FAILED
        : 140 actionable tasks: 5 executed, 135 up-to-date
        ERROR:/Users/Neil.Warner/dev/patrol/packages/patrol/example/build/geolocator_android/intermediates/runtime_library_classes_jar/debug/classes.jar: D8: java.lang.NullPointerException
        ERROR:/Users/Neil.Warner/dev/patrol/packages/patrol/example/build/flutter_local_notifications/intermediates/runtime_library_classes_jar/debug/classes.jar: D8: java.lang.NullPointerException
        ERROR:/Users/Neil.Warner/dev/patrol/packages/patrol/example/build/webview_flutter_android/intermediates/runtime_library_classes_jar/debug/classes.jar: D8: java.lang.NullPointerException
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':app:mergeLibDexDebug'.
        > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
           > Failed to transform classes.jar (project :geolocator_android) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, com.android.build.api.attributes.AgpVersionAttr=7.4.2, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.gradle.internal.attributes.VariantAttr=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
              > Execution failed for DexingWithClasspathTransform: /Users/Neil.Warner/dev/patrol/packages/patrol/example/build/geolocator_android/intermediates/runtime_library_classes_jar/debug/classes.jar.
                 > Error while dexing.
           > Failed to transform classes.jar (project :flutter_local_notifications) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, com.android.build.api.attributes.AgpVersionAttr=7.4.2, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.gradle.internal.attributes.VariantAttr=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
              > Execution failed for DexingWithClasspathTransform: /Users/Neil.Warner/dev/patrol/packages/patrol/example/build/flutter_local_notifications/intermediates/runtime_library_classes_jar/debug/classes.jar.
                 > Error while dexing.
           > Failed to transform classes.jar (project :webview_flutter_android) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, com.android.build.api.attributes.AgpVersionAttr=7.4.2, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.gradle.internal.attributes.VariantAttr=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
              > Execution failed for DexingWithClasspathTransform: /Users/Neil.Warner/dev/patrol/packages/patrol/example/build/webview_flutter_android/intermediates/runtime_library_classes_jar/debug/classes.jar.
                 > Error while dexing.
        
        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        
        * Get more help at https://help.gradle.org
        
        BUILD FAILED in 5s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (6.3s)
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      DevelopCommand._build (package:patrol_cli/src/commands/develop.dart:208:7)
<asynchronous suspension>
#4      DevelopCommand.run (package:patrol_cli/src/commands/develop.dart:180:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:318:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:262:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:68:20)
<asynchronous suspension>
#9      main (file:///Users/Neil.Warner/.pub-cache/hosted/pub.dev/patrol_cli-2.3.1+1/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      DevelopCommand._build (package:patrol_cli/src/commands/develop.dart:208:7)
<asynchronous suspension>
#4      DevelopCommand.run (package:patrol_cli/src/commands/develop.dart:180:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:318:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:262:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:68:20)
<asynchronous suspension>
#9      main (file:///Users/Neil.Warner/.pub-cache/hosted/pub.dev/patrol_cli-2.3.1+1/bin/main.dart:6:20)
<asynchronous suspension>

Neil.Warner@NA-PPH9L3DMBP example % 

```

</details>

### Patrol version

  patrol:
    path: ../
# cloned on 27-nov-2023

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Neil.Warner@NA-PPH9L3DMBP ~ % patrol doctor
Patrol CLI version: 2.3.1+1
Program adb found in /Users/Neil.Warner/Library/Android/sdk/platform-tools//adb
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)```

</details>


### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.6.2 22G320 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

```

</details>

**Comment by piotruela** [comment] 2023-11-28 07:32
Hi @neiljaywarner. Thanks for creating the issue. I couldn't reproduce it on the Android emulator (and I don't have access to a physical Android device rn). On what device and Android version are you trying to run the test?

**Comment by neiljaywarner** [comment] 2023-11-28 15:45
android 14 pixel 6 yesterday and just now today emulator with these properties (basically api level 29) you could use to recreate.
i'm on android studio giraffe.. 
java--version shows openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

although java version woudl come from google wrapper?
Properties
avd.ini.displayname              MDM Pixel 6a API 29 play store
avd.ini.encoding                 UTF-8
AvdId                            MDM_Pixel_6a_API_29_play_store
disk.dataPartition.size          6G
fastboot.chosenSnapshotFile
fastboot.forceChosenSnapshotBoot no
fastboot.forceColdBoot           no
fastboot.forceFastBoot           yes
hw.accelerometer                 yes
hw.arc                           false
hw.audioInput                    yes
hw.battery                       yes
hw.camera.back                   virtualscene
hw.camera.front                  emulated
hw.cpu.ncore                     4
hw.device.hash2                  MD5:437310fd48ee977d023133a2babae359
hw.device.manufacturer           Google
hw.device.name                   pixel_6a
hw.dPad                          no
hw.gps                           yes
hw.gpu.enabled                   yes
hw.gpu.mode                      auto
hw.initialOrientation            Portrait
hw.keyboard                      yes
hw.lcd.density                   420
hw.lcd.height                    2400
hw.lcd.width                     1080
hw.mainKeys                      no
hw.ramSize                       1536
hw.sdCard                        yes
hw.sensors.orientation           yes
hw.sensors.proximity             yes
hw.trackBall                     no
image.androidVersion.api         29
image.sysdir.1                   system-images/android-29/google_apis_playstore/arm64-v8a/
PlayStore.enabled                true
runtime.network.latency          none
runtime.network.speed            full
showDeviceFrame                  yes
skin.dynamic                     yes
tag.display                      Google Play
tag.id                           google_apis_playstore
vm.heapSize                      228

**Comment by neiljaywarner** [comment] 2023-11-28 18:01
@piotruela  i made a new branch and  removed from https://github.com/leancodepl/patrol/blob/master/packages/patrol/example/pubspec.yaml 
the below
  flutter_local_notifications: ^16.1.0
  geolocator: ^10.1.0
  webview_flutter: ^4.4.2


and their associated dart code and test code ad now the tests pass, although the patrol dev tools extension didn't work yet for me, which was what i'm trying to test/evaluate/document and i'm excited about

**Comment by piotruela** [comment] 2023-11-29 06:34
Glad to hear that you made that work. Since the issue pertains to running the test, and I couldn't reproduce that bug, I'm closing it for now.

**Closed by piotruela** 2023-11-29 06:34 UTC

**Comment by neiljaywarner** [comment] 2023-11-29 14:04
It's probably not too new. Hedgehog was in beta 3 months ago

Big Gradle changes though I think? Gradle 8 somewhere

....sent from my phone

**Comment by neiljaywarner** [comment] 2023-11-29 14:08
Actually you should be able to reproduce with emulator with Android studio
giraffe from stable?

I got it to work from iOS and sometimes from removing a bunch of stuff from
example project.

....sent from my phone

**Comment by bysano** [comment] 2023-12-01 09:26
the issue was that setup used not appropriate Java version , when i cahged it from 21 to 19 , that helped
