### ISSUE TITLE
Can we take screenshots using patrol.?

### ISSUE THREAD

**Issue by lravihs** [leancodepl/patrol#1527] opened 2023-07-13 08:06 UTC
### Steps to reproduce

To take screenshots while executing

### Actual results

To take screenshots while executing

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol:^2.0.3

### Patrol Doctor output

patrol doctor

### Flutter Doctor output

flutter doctor

**Comment by lravihs** [comment] 2023-07-13 09:49
It will be better if we are able to take a screenshot using a single method

**Comment by bartekpacia** [comment] 2023-07-13 09:57
Duplicate of #534.

**Closed by bartekpacia** 2023-07-13 09:57 UTC

**Comment by lravihs** [comment] 2023-07-14 05:21
Hi @bartekpacia I am not able to use host automator inside the script. Can you please help me how to use the host function .?
<img width="517" alt="Screenshot 2023-07-14 at 10 50 42 AM" src="https://github.com/leancodepl/patrol/assets/133226443/987da224-5484-4476-b81a-7ed2df6ebdef">

**Comment by bartekpacia** [comment] 2023-07-14 07:22
`hostAutomator` was only present in our pre-releases many months ago. It's not available.

**Comment by lravihs** [comment] 2023-07-14 08:09
Then taking screenshots is possible or not.?

**Comment by bartekpacia** [comment] 2023-07-14 08:12
Patrol doesn't currently have any support for that. You can try to use `flutter screenshot` manually, but of course this won't be then synchronized with your test in any way.

Most cloud device farms and CI platforms let you screen record screen, which is almost always much better than screenshots.

**Comment by lravihs** [comment] 2023-07-14 09:43
Does the screenshot issue be fixed in future.?

**Comment by bartekpacia** [comment] 2023-07-14 09:44
Yes, but no timelines.

**Comment by lravihs** [comment] 2023-07-14 09:46
Okay @bartekpacia . It will be appreciated if HOSTAUTOMATOR is enabled

**Comment by pandoras-toolbox** [comment] 2023-07-18 15:37
We cannot use device farms because of data privacy. I do not know what you mean with CI platforms @bartekpacia. We use Gitlab, I do not think it can do these screenshots. Also if using things like Cucumber then usually you want to integrate the screenshot into your Cucumber test report. I will try to find a way to create such a screenshot from within the Patrol test, that is what we need in our context.

**Comment by lravihs** [comment] 2023-07-20 04:57
@pandoras-toolbox Yes please. It will be better if we find a way to capture the screenshot wherever we wanted
