### ISSUE TITLE
Make it possible to scroll to a native widget

### ISSUE THREAD

**Issue by fylyppo** [leancodepl/patrol#1335] opened 2023-06-06 09:29 UTC
Something similar to already implemented Flutter Widget Finder's `.scrollTo()`.
It could look like: `await $.native.scrollTo();`

**Comment by bartekpacia** [comment] 2023-06-06 10:34
Kind of related to #499

**Comment by jBorkowska** [comment] 2023-07-12 11:50
Duplicate of #799, closing

**Closed by jBorkowska** 2023-07-12 11:50 UTC
Labels: feature, package: patrol, a: native automation
